# Project Charm — Session 2 update script
# Save as update.ps1 INSIDE your 'C:\Project Charm' folder, then run it.
# It overwrites the changed files and adds the new ones. Your .git folder
# is left untouched, so you can review/commit afterward as normal.

$root = $PSScriptRoot
if (-not (Test-Path (Join-Path $root "Charm.sln"))) {
    Write-Host "ERROR: run this from inside the Project Charm folder (Charm.sln not found here)." -ForegroundColor Red
    exit 1
}
Write-Host "Updating project in $root ..."

# docs/design.md
$f_docs_design_md_b64 = @(
    "IyBQcm9qZWN0IENoYXJtIOKAlCBEZXNpZ24gRG9jdW1lbnQKCldoeSB0aGluZ3MgYXJlIGJ1aWx0"
    "IHRoZSB3YXkgdGhleSBhcmUuIFRoaXMgZG9jdW1lbnQgcmVjb3JkcyByYXRpb25hbGUsIG5vdAp0"
    "YXNrIGxpc3RzICh0aG9zZSBsaXZlIGluIHRoZSBqb3VybmFsKS4gSXQgaXMgdXBkYXRlZCBldmVy"
    "eSBzZXNzaW9uLgoKLS0tCgojIyBUaGUgdW5pZm9ybSByb2xsIGNvbnRyYWN0CgpSb2xsIEEgaXMg"
    "dGhlIGZpcnN0IG5vZGUsIHNvIGl0cyBzaGFwZSBpcyB0aGUgdGVtcGxhdGUgZXZlcnkgbGF0ZXIg"
    "cm9sbCBpbmhlcml0cy4KQSByb2xsOgoKMS4gKipyZWNlaXZlcyoqIHRoZSBjdXJyZW50IGBQb3Nz"
    "ZXNzaW9uU3RhdGVgIHBsdXMgYSBmaW5pc2hlZCBgUGllYCAod2VpZ2h0ZWQgb2RkcwogICB0aGF0"
    "IGFscmVhZHkgc3VtIHRvIDEpOwoyLiAqKmNvbnN1bWVzKiogdGhlIHBpZSDigJQgaXQgcm9sbHMg"
    "YWdhaW5zdCBpdCBhbmQgbmV2ZXIgY29tcHV0ZXMgaXRzIG93biBvZGRzOwozLiAqKnJldHVybnMg"
    "b25lIHR5cGVkIHJlc3VsdCoqIOKAlCBhIGBUZXJtaW5hbGAgKHBvc3Nlc3Npb24gZW5kcykgb3Ig"
    "YSBgQ29udGludWVgCiAgIChzdGF0ZSBjYXJyaWVzIGZvcndhcmQpOwo0LiAqKm5hbWVzIG5vIHN1"
    "Y2Nlc3Nvci4qKiBUaGUgYFJlc29sdmVyYCByb3V0ZXMgYSBgQ29udGludWVgLgoKVGhlIHBvaW50"
    "IG9mIHRoZSBjb250cmFjdCBpcyB0dW5hYmlsaXR5IGFuZCBsZWdpYmlsaXR5OiBvZGRzIGFyZSBw"
    "cm9kdWNlZCBpbiBvbmUKcGxhY2UgKGEgZ2VuZXJhdG9yKSBhbmQgY29uc3VtZWQgaW4gYW5vdGhl"
    "ciAoYSByb2xsKSwgd2l0aCBhIHZhbGlkYXRlZCBzZWFtCmJldHdlZW4gdGhlbSwgc28gc2lnbmFs"
    "IGZsb3dzIG9uZSBkaXJlY3Rpb24gYW5kIG5vdGhpbmcgZmVlZHMgYmFjayBpbnRvIGl0c2VsZi4K"
    "CiMjIyBQaWUg4oCUIHRoZSBvZGRzIGN1cnJlbmN5CmBQaWU8VE91dGNvbWU+YCBpcyBnZW5lcmlj"
    "IG92ZXIgYSByb2xsJ3Mgb3V0Y29tZSBlbnVtLiBJdCAqKnZhbGlkYXRlcyBvbgpjb25zdHJ1Y3Rp"
    "b24qKjogZXZlcnkgb3V0Y29tZSBtdXN0IGhhdmUgYSBub24tbmVnYXRpdmUsIGZpbml0ZSB3ZWln"
    "aHQsIGFuZCB0aGUKd2VpZ2h0cyBtdXN0IHN1bSB0byAxIHdpdGhpbiBgRXBzaWxvbmAuIEJlY2F1"
    "c2UgYW4gaW52YWxpZCBwaWUgY2Fubm90IGJlCmNvbnN0cnVjdGVkLCAidmFsaWRhdGUgb24gcmVj"
    "ZWlwdCIgaXMgZW5mb3JjZWQgYnkgdGhlIHR5cGUg4oCUIGEgcm9sbCB0aGF0IGhvbGRzIGEKcGll"
    "IGhvbGRzIGEgdmFsaWQgb25lLCBhbmQgYSBmdXR1cmUgYnVnZ3kgZ2VuZXJhdG9yIGZhaWxzIGxv"
    "dWQgYXQgdGhlIG1vbWVudCBvZgpoYW5kLW9mZiBpbnN0ZWFkIG9mIHNpbGVudGx5IHJvbGxpbmcg"
    "Z2FyYmFnZS4gU2xpY2VzIGFyZSB3YWxrZWQgaW4gZW51bQpkZWNsYXJhdGlvbiBvcmRlciBzbyBh"
    "IGdpdmVuIFJORyBkcmF3IGFsd2F5cyBtYXBzIHRvIHRoZSBzYW1lIG91dGNvbWUuCgojIyMgUmVz"
    "dWx0IOKAlCBUZXJtaW5hbCB2cy4gQ29udGludWUKYFJvbGxSZXN1bHRgIGlzIGEgc2VhbGVkIHBh"
    "aXIuIGBUZXJtaW5hbChSZWFzb24sIFN0YXRlKWAgZW5kcyB0aGUgcG9zc2Vzc2lvbjsKYENvbnRp"
    "bnVlKE5leHQsIFN0YXRlKWAgY2FycmllcyBmb3J3YXJkLiBgRWxhcHNlZFNlY29uZHNgIGxpdmVz"
    "IG9uIHRoZSBiYXNlCnJlc3VsdCBhbmQgaXM6Ci0gKipudWxsKiogPSB0aW1lIG5vdCB5ZXQgYXBw"
    "b3J0aW9uZWQ7IGEgZnV0dXJlICp0aW1lIHJvbGwqIG93bnMgaXQgKHRoZSBub3JtYWwgY2FzZSk7"
    "Ci0gKipub24tbnVsbCoqID0gdGhlIGVsYXBzZWQgdGltZSBpcyBpbnZhcmlhbnQgYW5kIGFscmVh"
    "ZHkga25vd24gaGVyZS4KCk9ubHkgdGhlIHNob3QtY2xvY2sgdmlvbGF0aW9uIHNldHMgaXQgKHRv"
    "IHRoZSBmdWxsIGNsb2NrKS4gVGhpcyBrZWVwcyB0aW1la2VlcGluZwpvdXQgb2YgUm9sbCBBIHdo"
    "aWxlIGxldHRpbmcgdGhlIG9uZSBpbnZhcmlhbnQtdGltZSBvdXRjb21lIHN0YW1wIGl0c2VsZi4K"
    "CiMjIyAiTmFtZXMgbm8gc3VjY2Vzc29yIiwgcHJlY2lzZWx5CkEgYENvbnRpbnVlYCBjYXJyaWVz"
    "IGEgYENvbnRpbnVhdGlvbktpbmRgIChgSW50b0hhbGZjb3VydFNldGAsCmBSZXNvbHZlVHVybm92"
    "ZXJUeXBlYCwgYFJlc29sdmVGb3VsVHlwZWAsIGBSZXNvbHZlSnVtcEJhbGxgKSDigJQgYSAqY2F0"
    "ZWdvcnkgb2YgaXRzCm93biByZXN1bHQqLCBub3QgYSByZWZlcmVuY2UgdG8gYSBub2RlLiBUaGUg"
    "YFJlc29sdmVyYCBpcyB0aGUgc29sZSBwbGFjZSB0aGF0Cm1hcHMgYSBraW5kIHRvIGFuIGFjdHVh"
    "bCBzdWNjZXNzb3IuIFdoZW4gYSByZWFsIG5vZGUgcmVwbGFjZXMgYSBzdHViLCBvbmx5IHRoYXQK"
    "bWFwcGluZyBjaGFuZ2VzOyB0aGUgcm9sbCB0aGF0IGVtaXR0ZWQgdGhlIGNvbnRpbnVhdGlvbiBp"
    "cyBuZXZlciByZW9wZW5lZC4gVGhpcwppcyB0aGUgc2VhbSB0aGF0IGxldCBSb2xsIEEgYmUgYnVp"
    "bHQgYmVmb3JlIGFueSBvZiBpdHMgc3VjY2Vzc29ycyBleGlzdC4KCiMjIyBSTkcKUm9sbHMgZHJh"
    "dyBmcm9tIGFuIGluamVjdGVkIGBJUm5nYCwgc2VlZGFibGUsIHNvIGJhdGNoIHJ1bnMgYW5kIG9i"
    "c2VydmFiaWxpdHkgYXJlCnJlcHJvZHVjaWJsZS4KCi0tLQoKIyMgR2FtZVN0YXRlIOKAlCBwZXJz"
    "aXN0ZW50IGluZnJhc3RydWN0dXJlCgpgR2FtZVN0YXRlYCBob2xkcyBzdGF0ZSB0aGF0IHN1cnZp"
    "dmVzIEFDUk9TUyBwb3NzZXNzaW9ucywgdW5saWtlCmBQb3NzZXNzaW9uU3RhdGVgIChwZXItcG9z"
    "c2Vzc2lvbikuIEl0IGV4aXN0cyBiZWNhdXNlIHNvbWUgb3V0Y29tZXMgc2V0CmNvbmRpdGlvbnMg"
    "Y29uc3VtZWQgbGF0ZXIg4oCUIG1vc3QgaW1tZWRpYXRlbHksIHRoZSAqKnBvc3Nlc3Npb24gYXJy"
    "b3cqKiwgd2hpY2ggYQpqdW1wIGJhbGwgaW4gb25lIHBvc3Nlc3Npb24gdXNlcyB0byBkZWNpZGUg"
    "d2hvIGdldHMgdGhlIGJhbGwgaW4gYW5vdGhlci4KCkJ1aWx0IHRoaXMgc2Vzc2lvbiBhcyBhICoq"
    "c2tlbGV0b24qKjogdGhlIHBvc3Nlc3Npb24gYXJyb3cgaGFzIHJlYWwgYmVoYXZpb3IgKGl0CmZs"
    "aXBzIHZpYSBgRmxpcFBvc3Nlc3Npb25BcnJvd2ApOyBzY29yZSwgZm91bHMsIGFuZCB0aW1lb3V0"
    "cyBhcmUgcGxhY2Vob2xkZXIKZmllbGRzIOKAlCB0eXBlZCBhbmQgbmFtZWQgc28gdGhlIHNoYXBl"
    "IGlzIGRlZmluZWQsIGJ1dCBub3QgeWV0IHJlYWQgb3Igd3JpdHRlbgpkdXJpbmcgcG9zc2Vzc2lv"
    "biByZXNvbHV0aW9uLiBOb3RoaW5nIGluIFJvbGwgQSB0b3VjaGVzIGBHYW1lU3RhdGVgOyB0aGUg"
    "ZnV0dXJlCmp1bXAtYmFsbCBhbmQgc2NvcmluZyByZXNvbHZlcnMgd2lsbC4KCi0tLQoKIyMgUm9s"
    "bCBBIOKAlCBFbnRyeTogSW5ib3VuZHMgKERlYWQgQmFsbCkKCioqU2ltdWxhdGVzOioqIHRoZSBm"
    "aXJzdCB0b3VjaCBvZiBhIHBvc3Nlc3Npb24gdGhhdCBiZWdpbnMgd2l0aCBhIGRlYWQtYmFsbApp"
    "bmJvdW5kIHBhc3MuCgoqKlBpZSBzaGFwZToqKiBmaXZlIHNsaWNlcyBvdmVyIGBFbnRyeU91dGNv"
    "bWVgIOKAlCBgQ2xlYW5FbnRyeWAsIGBUdXJub3ZlcmAsCmBTaG90Q2xvY2tWaW9sYXRpb25gLCBg"
    "Rm91bGAsIGBKdW1wQmFsbGAuIChTdHViIHdlaWdodHMgdG9kYXk7IHNlZSBiZWxvdy4pCgoqKkZp"
    "dmUgZXhpdHM6KioKCnwgT3V0Y29tZSB8IFJlc3VsdCB8IFJvdXRlcyB0byB8CnwtLS18LS0tfC0t"
    "LXwKfCBDbGVhbiBlbnRyeSB8IGBDb250aW51ZShJbnRvSGFsZmNvdXJ0U2V0KWAgfCBoYWxmY291"
    "cnQtc2V0IG5vZGUgKihzdHViKSogfAp8IFR1cm5vdmVyIHwgYENvbnRpbnVlKFJlc29sdmVUdXJu"
    "b3ZlclR5cGUpYCB8IHR1cm5vdmVyLXR5cGUgcmVzb2x2ZXIgKihzdHViKSogfAp8IFNob3QtY2xv"
    "Y2sgdmlvbGF0aW9uIHwgYFRlcm1pbmFsKCJTaG90Q2xvY2tWaW9sYXRpb24iKWAsIGVsYXBzZWQg"
    "PSBmdWxsIGNsb2NrIHwgcG9zc2Vzc2lvbiBlbmRzLCBiYWxsIHN3aXRjaGVzIHwKfCBGb3VsIHwg"
    "YENvbnRpbnVlKFJlc29sdmVGb3VsVHlwZSlgIHwgZm91bC10eXBlIHJlc29sdmVyICooc3R1Yikq"
    "IHwKfCBKdW1wIGJhbGwgfCBgQ29udGludWUoUmVzb2x2ZUp1bXBCYWxsKWAgfCBqdW1wLWJhbGwg"
    "cmVzb2x2ZXIgKihzdHViKSogfAoKKipXaHkgdGhlIHZpb2xhdGlvbiBpcyB0aGUgb25seSB0ZXJt"
    "aW5hbC4qKiBBIHNob3QtY2xvY2sgdmlvbGF0aW9uIGlzIGludmFyaWFudDoKbm8gc2hvdCwgdGhl"
    "IGZ1bGwgY2xvY2sgb2ZmLCBuZXZlciBhbnkgbW9yZSBvciBsZXNzLiBUaGVyZSBpcyBubyBwYXRo"
    "IHZhcmlhbmNlIHRvCnNpbXVsYXRlIG9uIHRoZSB3YXkgdG8gaXQsIHNvIGNvbGxhcHNpbmcgaXQg"
    "aW50byBhIHNpbmdsZSB0ZXJtaW5hbCBhdCBlbnRyeSBpcwpzdHJpY3RseSBjaGVhcGVyIGFuZCBs"
    "b3NlcyBub3RoaW5nIOKAlCBhbmQgaXQgaXMgd2h5IGl0cyBlbGFwc2VkIHRpbWUgY2FuIGJlCnN0"
    "YW1wZWQgb24gdGhlIHJlc3VsdCB3aXRoIG5vIHRpbWUgcm9sbC4KCioqV2h5IGZvdWwgYW5kIGp1"
    "bXAgYmFsbCBhcmUgY29udGludWVzLCBub3QgdGVybWluYWxzLioqIEJvdGggaGF2ZSByZWFsIHZh"
    "cmlhbmNlCmluIHdoYXQgdGhleSBiZWNvbWUuIEEgZm91bCBzdGlsbCBuZWVkcyBpdHMgdHlwZSBk"
    "ZWNpZGVkIChkZWZlbnNpdmUgbm9uLXNob290aW5nCnZzLiBvZmZlbnNpdmUpIGFuZCB3aGF0IHRo"
    "YXQgdHJpZ2dlcnMg4oCUIGEgZnV0dXJlIHJvbGwgKEQvRS/igKYpIGFuZCBwb3NzaWJseSBhCnBv"
    "c3Nlc3Npb24gY2hhbmdlLiBBIGp1bXAgYmFsbCBuZWVkcyB0aGUgcG9zc2Vzc2lvbiBhcnJvdyBj"
    "b25zdWx0ZWQuIEZvbGxvd2luZwp0aGUgdHVybm92ZXIgcGF0dGVybiwgUm9sbCBBIG9ubHkgY2xh"
    "c3NpZmllcyB0aGF0IHRoZSBvdXRjb21lIG9jY3VycmVkIGFuZCBoYW5kcwpvZmY7IHRoZSBkb3du"
    "c3RyZWFtIHJlc29sdmVyIGRvZXMgdGhlIGRlY2lkaW5nLgoKKipXaHkgdGltZSBpcyBvdGhlcndp"
    "c2UgYWJzZW50IGZyb20gUm9sbCBBLioqIEdhbWUtY2xvY2sgc2Vjb25kcyBhcmUgdGhlaXIgb3du"
    "CmZ1dHVyZSByb2xsLiBSb2xsIEEgaXMgdGltZWxlc3Mgb24gaXRzIGNvbnRpbnVlIHBhdGhzOyB0"
    "aGUgcmVzb2x2ZXIgd2lsbCByb3V0ZSB0bwp0aGUgdGltZSByb2xsIGRvd25zdHJlYW0uIFRoZSB2"
    "aW9sYXRpb24gaXMgdGhlIGxvbmUgZXhjZXB0aW9uLCBmb3IgdGhlIGludmFyaWFudApyZWFzb24g"
    "YWJvdmUuCgoqKlRoZSBwaWUgZ2VuZXJhdG9yIGlzIHN0dWJiZWQuKiogYFN0dWJQaWVHZW5lcmF0"
    "b3JgIHJldHVybnMgdGhlIGNvbmZpZ3VyZWQgYmFzZQp3ZWlnaHRzIHdpdGggb25lIGxpdmUgd2ly"
    "ZTogYSBzaW5nbGUgMOKAkzEgYHByZXNzdXJlYCBzY2FsYXIgbnVkZ2VzIHRoZSB0dXJub3Zlcgpz"
    "bGljZSAodGhlbiByZW5vcm1hbGl6ZXMpLiBUaGlzIGlzIGEgcGxhY2Vob2xkZXIgdG8gcHJvdmUg"
    "dGhlIGdlbmVyYXRvcuKGknJvbGwgc2VhbQpjYXJyaWVzIHNpZ25hbCDigJQgKipub3QqKiBiYXNr"
    "ZXRiYWxsIGxvZ2ljLiBUaGUgcmVhbCBhdHRyaWJ1dGUg4oaSIG1hdGNodXAg4oaSIHBpZQpnZW5l"
    "cmF0b3Igd2lsbCByZXBsYWNlIHRoaXMgc3R1YiB3aXRob3V0IHRvdWNoaW5nIFJvbGwgQS4KCioq"
    "RGlzY2lwbGluZSBpbiBwbGFjZSBmcm9tIGxpbmUgb25lLioqIEV2ZXJ5IG51bWJlciBpcyBpbiBg"
    "Y29uZmlnLmpzb25gCihgUm9sbEFDb25maWdgKTsgbm90aGluZyBpcyBoYXJkY29kZWQuIEFueSBw"
    "aWUgY2FuIGJlIHByaW50ZWQgd2l0aCBpdHMgaW5wdXRzIGFuZApyZXN1bHRpbmcgb3V0Y29tZS4g"
    "QSAxMDBrIGJhdGNoIGhhcm5lc3MgY29uZmlybXMgdGhlIGZpdmUgb3V0Y29tZSByYXRlcyBtYXRj"
    "aCB0aGUKY29uZmlndXJlZCBwaWUgd2l0aGluIHRvbGVyYW5jZSBhbmQgdGhhdCBldmVyeSBleGl0"
    "IGhhbmRzIG9mZiBjbGVhbmx5ICh0aGUKdGVybWluYWwgZW5kcywgZXZlcnkgY29udGludWUgcm91"
    "dGVzIHRvIGl0cyBzdHViKS4KCi0tLQoKIyMgUm9sbCB0YWJsZSBvZiBjb250ZW50cwoKfCBSb2xs"
    "IHwgTmFtZSB8IFN0YXR1cyB8CnwtLS18LS0tfC0tLXwKfCBBIHwgRW50cnkg4oCUIEluYm91bmRz"
    "IChEZWFkIEJhbGwpIHwgQnVpbHQgKHN0dWJiZWQgZ2VuZXJhdG9yICsgc3R1YmJlZCBzdWNjZXNz"
    "b3JzKSB8CgojIyBLbm93biByZXF1aXJlZCBpbmZyYXN0cnVjdHVyZSAobm90IHlldCBidWlsdCkK"
    "Ci0gKipQb3NzZXNzaW9uIGFycm93IHRyYWNrZXIqKiDigJQgc2tlbGV0b24gZXhpc3RzIG9uIGBH"
    "YW1lU3RhdGVgOyB0aGUganVtcC1iYWxsCiAgcmVzb2x2ZXIgdGhhdCBjb25zdW1lcyBhbmQgZmxp"
    "cHMgaXQgaXMgYSBmdXR1cmUgcm9sbC4KLSAqKkZvdWwtdHlwZSByZXNvbHZlcioqIOKAlCBkZWNp"
    "ZGVzIGRlZmVuc2l2ZSBub24tc2hvb3RpbmcgdnMuIG9mZmVuc2l2ZSBhbmQgd2hhdAogIHJvbGwg"
    "LyBwb3NzZXNzaW9uIGNoYW5nZSBpdCB0cmlnZ2Vycy4KLSAqKlRpbWUgcm9sbCoqIOKAlCBhcHBv"
    "cnRpb25zIGdhbWUtY2xvY2sgc2Vjb25kcyBmb3Igbm9uLWludmFyaWFudCBvdXRjb21lcy4K"
)
$f_docs_design_md_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_docs_design_md_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "docs\design.md"), $f_docs_design_md_bytes)
Write-Host "  wrote docs/design.md"

# docs/journal.md
$f_docs_journal_md_b64 = @(
    "IyBQcm9qZWN0IENoYXJtIOKAlCBTZXNzaW9uIEpvdXJuYWwKCk5ld2VzdCBlbnRyaWVzIGZpcnN0"
    "LiBXaGF0IHdhcyBidWlsdCwgZGVjaWRlZCwgYW5kIGxlZnQgc3R1YmJlZCBlYWNoIHNlc3Npb24u"
    "CgotLS0KCiMjIFNlc3Npb24gMiDigJQgRm91bHMsIGp1bXAgYmFsbHMsIGFuZCB0aGUgR2FtZVN0"
    "YXRlIHNrZWxldG9uCgoqKkJ1aWx0KioKLSBSb2xsIEEncyBwaWUgd2VudCBmcm9tIHRocmVlIHNs"
    "aWNlcyB0byAqKmZpdmUqKjogY2xlYW4gLyB0dXJub3ZlciAvIHZpb2xhdGlvbiAvCiAgZm91bCAv"
    "IGp1bXAgYmFsbC4KLSBgRm91bGAgLT4gYENvbnRpbnVlKFJlc29sdmVGb3VsVHlwZSlgIGFuZCBg"
    "SnVtcEJhbGxgIC0+IGBDb250aW51ZShSZXNvbHZlSnVtcEJhbGwpYCwKICBmb2xsb3dpbmcgdGhl"
    "IHR1cm5vdmVyIHBhdHRlcm4gKGNsYXNzaWZ5LCBoYW5kIG9mZiwgZGVjaWRlIGRvd25zdHJlYW0p"
    "LgotIGBGb3VsVHlwZVJlc29sdmVyU3R1YmAgYW5kIGBKdW1wQmFsbFJlc29sdmVyU3R1YmAgYWRk"
    "ZWQgc28gYm90aCBuZXcgZXhpdHMgYXJlCiAgYWNjb3VudGVkIGZvci4KLSBgR2FtZVN0YXRlYCBz"
    "a2VsZXRvbjogcGVyc2lzdGVudCBhY3Jvc3MgcG9zc2Vzc2lvbnMuIFBvc3Nlc3Npb24gYXJyb3cK"
    "ICAoYFRlYW1TaWRlYCBIb21lL0F3YXkpIHdpdGggYSB3b3JraW5nIGBGbGlwUG9zc2Vzc2lvbkFy"
    "cm93YC4gU2NvcmUsIHRlYW0gZm91bHMsCiAgYW5kIHRpbWVvdXRzIGFzIHR5cGVkIHBsYWNlaG9s"
    "ZGVyIGZpZWxkcywgbm90IHlldCB3aXJlZC4KLSBDb25maWcgZ2FpbmVkIGBCYXNlRm91bGAgYW5k"
    "IGBCYXNlSnVtcEJhbGxgOyBoYXJuZXNzIGNvdW50cyBhbGwgZml2ZSBvdXRjb21lcwogIGFuZCBk"
    "ZW1vbnN0cmF0ZXMgdGhlIGFycm93IGZsaXAuCi0gVGFyZ2V0IGZyYW1ld29yayBtb3ZlZCB0byBu"
    "ZXQxMC4wIHRvIG1hdGNoIHRoZSBsb2NhbCBtYWNoaW5lLgoKKipWZXJpZmllZCAoaGFybmVzcyBy"
    "dW4pKioKLSAxMDBrIGJhdGNoOiBhbGwgZml2ZSByYXRlcyBtYXRjaCB0aGUgY29uZmlndXJlZCBw"
    "aWUgd2l0aGluIHRvbGVyYW5jZQogIChjbGVhbiA4OC4wIC8gdHVybm92ZXIgNi4wIC8gdmlvbGF0"
    "aW9uIDIuMCAvIGZvdWwgMy4wIC8ganVtcCBiYWxsIDEuMCkuCi0gQ2xlYW4gaGFuZC1vZmY6IDk3"
    "LDk3MSByb3V0ZWQgKyAyLDAyOSBlbmRlZCA9IDEwMCwwMDAsIHplcm8gdW5yb3V0ZWQuCi0gUG9z"
    "c2Vzc2lvbiBhcnJvdyBmbGlwcyBIb21lIC0+IEF3YXkuCi0gU2VhbSBzdGlsbCBjYXJyaWVzIHNp"
    "Z25hbDogdHVybm92ZXIgNi4wJSAocHJlc3N1cmUgMCkgLT4gMTQuNSUgKHByZXNzdXJlIDEpLgoK"
    "KipEZWNpZGVkKioKLSBGb3VscyBhbmQganVtcCBiYWxscyBhcmUgb3B0aW9ucyBvbiAoZXZlbnR1"
    "YWxseSkgdmlydHVhbGx5IGV2ZXJ5IHBpZTsgYm90aCBhcmUKICBjb250aW51ZXMgYmVjYXVzZSB0"
    "aGV5IGhhdmUgcmVhbCB2YXJpYW5jZSwgdW5saWtlIHRoZSBpbnZhcmlhbnQgdmlvbGF0aW9uLgot"
    "IFRoZSBwb3NzZXNzaW9uIGFycm93IG11c3QgYmUgdHJhY2tlZCBwZXJzaXN0ZW50bHksIHNvIGl0"
    "IGxpdmVzIG9uIGBHYW1lU3RhdGVgLAogIG5vdCBgUG9zc2Vzc2lvblN0YXRlYC4KLSBgR2FtZVN0"
    "YXRlYCBpcyBidWlsdCBhcyBhIGRlZmluZWQtYnV0LWluZXJ0IHNrZWxldG9uIHRoaXMgc2Vzc2lv"
    "biDigJQgYXJyb3cgZmxpcHMsCiAgZXZlcnl0aGluZyBlbHNlIGlzIGEgcGxhY2Vob2xkZXIgZmll"
    "bGQgd2l0aCBubyByZXNvbHV0aW9uIGxvZ2ljLgoKKipMZWZ0IHN0dWJiZWQgKG91dCBvZiBzY29w"
    "ZSwgdW50b3VjaGVkKSoqCi0gRm91bC10eXBlIHJlc29sdmVyIChkZWZlbnNpdmUgbm9uLXNob290"
    "aW5nIHZzLiBvZmZlbnNpdmUsIGFuZCBpdHMgdHJpZ2dlcnMpLgotIEp1bXAtYmFsbCByZXNvbHZl"
    "ciAoY29uc3VtaW5nL2ZsaXBwaW5nIHRoZSBhcnJvdykuCi0gUmVhbCBhdHRyaWJ1dGUgLT4gcGll"
    "IGdlbmVyYXRvcjsgaGFsZmNvdXJ0LXNldCBub2RlOyB0dXJub3Zlci10eXBlIHJlc29sdmVyLgot"
    "IFNjb3JlL2ZvdWwvdGltZW91dCB0cmFja2luZyBsb2dpYyBvbiBgR2FtZVN0YXRlYC4KLSBUcmFu"
    "c2l0aW9uLCByZWJvdW5kcywgbGl2ZS1iYWxsLXN0ZWFsIGVudHJpZXM7IGFueSByb2xsIG90aGVy"
    "IHRoYW4gQS4KCi0tLQoKIyMgU2Vzc2lvbiAxIOKAlCBCdWlsZCBSb2xsIEEgKEVudHJ5OiBJbmJv"
    "dW5kcywgRGVhZCBCYWxsKQoKKipCdWlsdCoqCi0gUmVwbyBzY2FmZm9sZGluZzogYENoYXJtLnNs"
    "bmAsIC5ORVQgYC5naXRpZ25vcmVgLCBgQ2hhcm0uRW5naW5lYCAoY2xhc3MgbGlicmFyeSkKICBh"
    "bmQgYENoYXJtLkhhcm5lc3NgIChjb25zb2xlIGFwcCkuCi0gVGhlIHVuaWZvcm0gcm9sbCBjb250"
    "cmFjdCB0aGF0IGV2ZXJ5IGxhdGVyIHJvbGwgd2lsbCBmb2xsb3c6CiAgLSBgUGllPFRPdXRjb21l"
    "PmAg4oCUIGdlbmVyaWMgd2VpZ2h0ZWQtb2RkcyBjb250YWluZXIsIHZhbGlkYXRlcyBvbiBjb25z"
    "dHJ1Y3Rpb24uCiAgLSBgUm9sbFJlc3VsdGAg4oCUIHNlYWxlZCBgVGVybWluYWxgIC8gYENvbnRp"
    "bnVlYCwgd2l0aCBudWxsYWJsZSBgRWxhcHNlZFNlY29uZHNgLgogIC0gYENvbnRpbnVhdGlvbktp"
    "bmRgIOKAlCBhIGNvbnRpbnVlIGNhcnJpZXMgYSByZXN1bHQgY2F0ZWdvcnksIG5vdCBhIHN1Y2Nl"
    "c3Nvci4KICAtIGBJUm5nYCAvIGBTeXN0ZW1SbmdgIOKAlCBzZWVkYWJsZSByYW5kb21uZXNzIGZv"
    "ciByZXByb2R1Y2liaWxpdHkuCi0gYFJvbGxBLkV4ZWN1dGVgOyBgU3R1YlBpZUdlbmVyYXRvcmAg"
    "d2l0aCBvbmUgbGl2ZSBgcHJlc3N1cmVgIHdpcmU7IGBSZXNvbHZlcmAKICBwbHVzIGhhbGZjb3Vy"
    "dCBhbmQgdHVybm92ZXIgc3R1YnM7IGBSb2xsQUNvbmZpZ2AgKyBgY29uZmlnLmpzb25gOyBoYXJu"
    "ZXNzIHdpdGgKICBvYnNlcnZhYmlsaXR5LCAxMDBrIGJhdGNoIGNoZWNrLCBhbmQgcHJlc3N1cmUt"
    "c2lnbmFsIGNoZWNrLgoKKipEZWNpZGVkKioKLSBSb2xsIEEgaXMgdGltZWxlc3MgZXhjZXB0IHRo"
    "ZSB2aW9sYXRpb24gdGVybWluYWwsIHdoaWNoIHN0YW1wcyBpdHMgb3duCiAgaW52YXJpYW50IGVs"
    "YXBzZWQgdGltZS4gQWxsIG90aGVyIHRpbWUgaXMgYSBmdXR1cmUgdGltZSByb2xsLgotIFRoZSB2"
    "aW9sYXRpb24gbGl2ZXMgYXMgYSB0ZXJtaW5hbCBhdCBlbnRyeSBiZWNhdXNlIGl0IGhhcyBubyBw"
    "YXRoIHZhcmlhbmNlLgotIFBpZSB2YWxpZGF0aW9uIGxpdmVzIGF0IGNvbnN0cnVjdGlvbiA9IHRo"
    "ZSBnZW5lcmF0b3ItPnJvbGwgc2VhbS4KLSBBIGNvbnRpbnVlIG5hbWVzIGEgYENvbnRpbnVhdGlv"
    "bktpbmRgLCBuZXZlciBhIG5vZGU7IHRoZSByZXNvbHZlciBvd25zIHJvdXRpbmcuCg=="
)
$f_docs_journal_md_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_docs_journal_md_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "docs\journal.md"), $f_docs_journal_md_bytes)
Write-Host "  wrote docs/journal.md"

# src/Charm.Engine/Charm.Engine.csproj
$f_src_Charm_Engine_Charm_Engine_csproj_b64 = @(
    "PFByb2plY3QgU2RrPSJNaWNyb3NvZnQuTkVULlNkayI+CgogIDxQcm9wZXJ0eUdyb3VwPgogICAg"
    "PFRhcmdldEZyYW1ld29yaz5uZXQxMC4wPC9UYXJnZXRGcmFtZXdvcms+CiAgICA8SW1wbGljaXRV"
    "c2luZ3M+ZW5hYmxlPC9JbXBsaWNpdFVzaW5ncz4KICAgIDxOdWxsYWJsZT5lbmFibGU8L051bGxh"
    "YmxlPgogICAgPFJvb3ROYW1lc3BhY2U+Q2hhcm0uRW5naW5lPC9Sb290TmFtZXNwYWNlPgogIDwv"
    "UHJvcGVydHlHcm91cD4KCjwvUHJvamVjdD4K"
)
$f_src_Charm_Engine_Charm_Engine_csproj_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_Charm_Engine_csproj_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\Charm.Engine.csproj"), $f_src_Charm_Engine_Charm_Engine_csproj_bytes)
Write-Host "  wrote src/Charm.Engine/Charm.Engine.csproj"

# src/Charm.Engine/Config.cs
$f_src_Charm_Engine_Config_cs_b64 = @(
    "dXNpbmcgU3lzdGVtLlRleHQuSnNvbjsKCm5hbWVzcGFjZSBDaGFybS5FbmdpbmU7CgovLy8gPHN1"
    "bW1hcnk+Ci8vLyBFdmVyeSB0dW5hYmxlIG51bWJlciBmb3IgUm9sbCBBIGxpdmVzIGhlcmUg4oCU"
    "IG5vdGhpbmcgaXMgaGFyZGNvZGVkIGluIGxvZ2ljLgovLy8gTG9hZGVkIGZyb20gY29uZmlnLmpz"
    "b24gc28gdmFsdWVzIGNhbiBiZSBlZGl0ZWQgd2l0aG91dCB0b3VjaGluZyBjb2RlLgovLy8gPC9z"
    "dW1tYXJ5PgpwdWJsaWMgc2VhbGVkIGNsYXNzIFJvbGxBQ29uZmlnCnsKICAgIC8vIC0tLSBTdHVi"
    "IHBpZSBiYXNlIHdlaWdodHMgKHBsYWNlaG9sZGVyczsgdGhlIHJlYWwgYXR0cmlidXRlLWRyaXZl"
    "bgogICAgLy8gICAgIGdlbmVyYXRvciB3aWxsIHJlcGxhY2UgdGhlc2UpLiBUaGUgZ2VuZXJhdG9y"
    "IHJlbm9ybWFsaXplcywgYnV0IHRoZXNlCiAgICAvLyAgICAgYXJlIGtlcHQgc3VtbWluZyB0byAx"
    "IGZvciBjbGFyaXR5LiAtLS0KICAgIHB1YmxpYyBkb3VibGUgQmFzZUNsZWFuIHsgZ2V0OyBzZXQ7"
    "IH0gPSAwLjg4OwogICAgcHVibGljIGRvdWJsZSBCYXNlVHVybm92ZXIgeyBnZXQ7IHNldDsgfSA9"
    "IDAuMDY7CiAgICBwdWJsaWMgZG91YmxlIEJhc2VWaW9sYXRpb24geyBnZXQ7IHNldDsgfSA9IDAu"
    "MDI7CiAgICBwdWJsaWMgZG91YmxlIEJhc2VGb3VsIHsgZ2V0OyBzZXQ7IH0gPSAwLjAzOwogICAg"
    "cHVibGljIGRvdWJsZSBCYXNlSnVtcEJhbGwgeyBnZXQ7IHNldDsgfSA9IDAuMDE7CgogICAgLy8v"
    "IDxzdW1tYXJ5PlRoZSBzaW5nbGUgbGl2ZSB3aXJlIHByb3ZpbmcgdGhlIHNlYW0gY2FycmllcyBz"
    "aWduYWw6IGhvdyBtdWNoCiAgICAvLy8gYSBwcmVzc3VyZSBvZiAxLjAgYWRkcyB0byB0aGUgdHVy"
    "bm92ZXIgd2VpZ2h0IGJlZm9yZSByZW5vcm1hbGl6YXRpb24uCiAgICAvLy8gUGxhY2Vob2xkZXIs"
    "IG5vdCBiYXNrZXRiYWxsIGxvZ2ljLjwvc3VtbWFyeT4KICAgIHB1YmxpYyBkb3VibGUgUHJlc3N1"
    "cmVUdXJub3Zlck51ZGdlIHsgZ2V0OyBzZXQ7IH0gPSAwLjEwOwoKICAgIC8vLyA8c3VtbWFyeT5J"
    "bnZhcmlhbnQgZWxhcHNlZCB0aW1lIHN0YW1wZWQgb24gYSBzaG90LWNsb2NrLXZpb2xhdGlvbgog"
    "ICAgLy8vIHRlcm1pbmFsOiB0aGUgZnVsbCBzaG90IGNsb2NrIChOQ0FBIG1lbidzID0gMzBzKS48"
    "L3N1bW1hcnk+CiAgICBwdWJsaWMgZG91YmxlIFZpb2xhdGlvbkVsYXBzZWRTZWNvbmRzIHsgZ2V0"
    "OyBzZXQ7IH0gPSAzMC4wOwoKICAgIC8vLyA8c3VtbWFyeT5Ub2xlcmFuY2UgZm9yIHRoZSBwaWUg"
    "c3VtLXRvLW9uZSB2YWxpZGF0aW9uLjwvc3VtbWFyeT4KICAgIHB1YmxpYyBkb3VibGUgRXBzaWxv"
    "biB7IGdldDsgc2V0OyB9ID0gMWUtOTsKCiAgICAvLyAtLS0gQmF0Y2ggaGFybmVzcyBzZXR0aW5n"
    "cyAtLS0KICAgIHB1YmxpYyBpbnQgQmF0Y2hTaXplIHsgZ2V0OyBzZXQ7IH0gPSAxMDBfMDAwOwoK"
    "ICAgIC8vLyA8c3VtbWFyeT5BbGxvd2VkIGFic29sdXRlIGdhcCBiZXR3ZWVuIGFuIG9ic2VydmVk"
    "IHJhdGUgYW5kIGl0cyBjb25maWd1cmVkCiAgICAvLy8gd2VpZ2h0IGluIHRoZSBiYXRjaCBoYXJu"
    "ZXNzLjwvc3VtbWFyeT4KICAgIHB1YmxpYyBkb3VibGUgUmF0ZVRvbGVyYW5jZSB7IGdldDsgc2V0"
    "OyB9ID0gMC4wMDU7CgogICAgcHVibGljIGludCBTZWVkIHsgZ2V0OyBzZXQ7IH0gPSAyMDI2MDYx"
    "MDsKCiAgICBwdWJsaWMgc3RhdGljIFJvbGxBQ29uZmlnIExvYWQoc3RyaW5nIHBhdGgpCiAgICB7"
    "CiAgICAgICAgdmFyIGpzb24gPSBGaWxlLlJlYWRBbGxUZXh0KHBhdGgpOwogICAgICAgIHZhciBj"
    "ZmcgPSBKc29uU2VyaWFsaXplci5EZXNlcmlhbGl6ZTxSb2xsQUNvbmZpZz4oCiAgICAgICAgICAg"
    "IGpzb24sIG5ldyBKc29uU2VyaWFsaXplck9wdGlvbnMgeyBQcm9wZXJ0eU5hbWVDYXNlSW5zZW5z"
    "aXRpdmUgPSB0cnVlIH0pOwogICAgICAgIHJldHVybiBjZmcgPz8gdGhyb3cgbmV3IEludmFsaWRP"
    "cGVyYXRpb25FeGNlcHRpb24oJCJDb3VsZCBub3QgcGFyc2UgY29uZmlnIGF0IHtwYXRofS4iKTsK"
    "ICAgIH0KfQo="
)
$f_src_Charm_Engine_Config_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_Config_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\Config.cs"), $f_src_Charm_Engine_Config_cs_bytes)
Write-Host "  wrote src/Charm.Engine/Config.cs"

# src/Charm.Engine/EntryOutcomes.cs
$f_src_Charm_Engine_EntryOutcomes_cs_b64 = @(
    "bmFtZXNwYWNlIENoYXJtLkVuZ2luZTsKCi8vLyA8c3VtbWFyeT4KLy8vIFRoZSBvdXRjb21lcyBS"
    "b2xsIEEgKGRlYWQtYmFsbCBpbmJvdW5kIGVudHJ5KSBjYW4gcmVzb2x2ZSB0by4gVGhpcyBlbnVt"
    "Ci8vLyBkZWZpbmVzIHRoZSBzbGljZXMgb2YgUm9sbCBBJ3MgcGllLiBEZWNsYXJhdGlvbiBvcmRl"
    "ciBpcyBzaWduaWZpY2FudDoKLy8vIDxzZWUgY3JlZj0iUGlle1RPdXRjb21lfSIvPiB3YWxrcyBz"
    "bGljZXMgaW4gdGhpcyBvcmRlciwgc28gdGhlIHNhbWUgUk5HIGRyYXcKLy8vIGFsd2F5cyBtYXBz"
    "IHRvIHRoZSBzYW1lIG91dGNvbWUgKHJlcHJvZHVjaWJpbGl0eSkuCi8vLyA8L3N1bW1hcnk+CnB1"
    "YmxpYyBlbnVtIEVudHJ5T3V0Y29tZQp7CiAgICAvLy8gPHN1bW1hcnk+T2ZmZW5zZSBnZXRzIGNs"
    "ZWFubHkgaW50byBpdHMgaGFsZmNvdXJ0IHNldC4gLT4gQ09OVElOVUUuPC9zdW1tYXJ5PgogICAg"
    "Q2xlYW5FbnRyeSwKCiAgICAvLy8gPHN1bW1hcnk+T2ZmZW5zZSBjb3VnaHMgaXQgdXAgb24gdGhl"
    "IGVudHJ5LiAtPiBDT05USU5VRSAodG8gdHVybm92ZXItdHlwZSByZXNvbHZlcikuPC9zdW1tYXJ5"
    "PgogICAgVHVybm92ZXIsCgogICAgLy8vIDxzdW1tYXJ5PgogICAgLy8vIE5vIHNob3QsIGZ1bGwg"
    "c2hvdCBjbG9jayBidXJuZWQuIC0+IFRFUk1JTkFMLiBJbnZhcmlhbnQ6IGEgc2hvdC1jbG9jawog"
    "ICAgLy8vIHZpb2xhdGlvbiBpcyBhbHdheXMgdGhlIGZ1bGwgY2xvY2sgb2ZmLCBuZXZlciBtb3Jl"
    "IG9yIGxlc3MsIHNvIGl0cwogICAgLy8vIGVsYXBzZWQgdGltZSBpcyBrbm93biBoZXJlIGFuZCBu"
    "ZWVkcyBubyBzZXBhcmF0ZSB0aW1lIHJvbGwuCiAgICAvLy8gPC9zdW1tYXJ5PgogICAgU2hvdENs"
    "b2NrVmlvbGF0aW9uLAoKICAgIC8vLyA8c3VtbWFyeT5BIGZvdWwgb24gdGhlIGluYm91bmQvZW50"
    "cnkuIC0+IENPTlRJTlVFICh0byBmb3VsLXR5cGUgcmVzb2x2ZXIsCiAgICAvLy8gd2hpY2ggd2ls"
    "bCBkZWNpZGUgZGVmZW5zaXZlIG5vbi1zaG9vdGluZyB2cy4gb2ZmZW5zaXZlIGFuZCB3aGF0IGl0"
    "CiAgICAvLy8gdHJpZ2dlcnMpLiBIYXMgcmVhbCB2YXJpYW5jZSwgc28gaXQgaXMgbmV2ZXIgcmVz"
    "b2x2ZWQgaGVyZS48L3N1bW1hcnk+CiAgICBGb3VsLAoKICAgIC8vLyA8c3VtbWFyeT5BIHRpZS11"
    "cCAvIGhlbGQgYmFsbCBvbiB0aGUgaW5ib3VuZC4gLT4gQ09OVElOVUUgKHRvIGp1bXAtYmFsbAog"
    "ICAgLy8vIHJlc29sdmVyLCB3aGljaCBjb25zdWx0cyB0aGUgcG9zc2Vzc2lvbiBhcnJvdyBvbiBH"
    "YW1lU3RhdGUpLiBSYXJlIGJ1dAogICAgLy8vIHJlYWwgb24gdmlydHVhbGx5IGV2ZXJ5IHBpZSBn"
    "b2luZyBmb3J3YXJkLjwvc3VtbWFyeT4KICAgIEp1bXBCYWxsCn0KCi8vLyA8c3VtbWFyeT4KLy8v"
    "IFRoZSBzZW1hbnRpYyBjYXRlZ29yeSBvZiBhIENPTlRJTlVFIHJlc3VsdC4gQSByb2xsIGNsYXNz"
    "aWZpZXMgKndoYXQga2luZCoKLy8vIG9mIGNvbnRpbnVhdGlvbiBpdCBwcm9kdWNlZDsgaXQgbmV2"
    "ZXIgbmFtZXMgdGhlIHN1Y2Nlc3NvciBub2RlLiBUaGUKLy8vIDxzZWUgY3JlZj0iUmVzb2x2ZXIi"
    "Lz4gb3ducyB0aGUgbWFwcGluZyBmcm9tIGEga2luZCB0byB0aGUgYWN0dWFsIG5leHQgbm9kZS4K"
    "Ly8vIEFkZGluZyBhIG5vZGUgbGF0ZXIgY2hhbmdlcyBvbmx5IHRoYXQgbWFwcGluZywgbmV2ZXIg"
    "dGhlIHJvbGwgdGhhdCBlbWl0dGVkCi8vLyB0aGUgY29udGludWF0aW9uLiBUaGlzIGlzIHRoZSBz"
    "ZWFtIHRoYXQgbGV0cyBSb2xsIEEgYmUgYnVpbHQgYmVmb3JlIGl0cwovLy8gc3VjY2Vzc29ycyBl"
    "eGlzdC4KLy8vIDwvc3VtbWFyeT4KcHVibGljIGVudW0gQ29udGludWF0aW9uS2luZAp7CiAgICAv"
    "Ly8gPHN1bW1hcnk+Q2xlYW4gZW50cnk6IGhhbmQgb2ZmIHRvIHRoZSAoc3R1YmJlZCkgaGFsZmNv"
    "dXJ0LXNldCBub2RlLjwvc3VtbWFyeT4KICAgIEludG9IYWxmY291cnRTZXQsCgogICAgLy8vIDxz"
    "dW1tYXJ5PlR1cm5vdmVyOiBoYW5kIG9mZiB0byB0aGUgKHN0dWJiZWQpIHR1cm5vdmVyLXR5cGUg"
    "cmVzb2x2ZXIuPC9zdW1tYXJ5PgogICAgUmVzb2x2ZVR1cm5vdmVyVHlwZSwKCiAgICAvLy8gPHN1"
    "bW1hcnk+Rm91bDogaGFuZCBvZmYgdG8gdGhlIChzdHViYmVkKSBmb3VsLXR5cGUgcmVzb2x2ZXIu"
    "PC9zdW1tYXJ5PgogICAgUmVzb2x2ZUZvdWxUeXBlLAoKICAgIC8vLyA8c3VtbWFyeT5KdW1wIGJh"
    "bGw6IGhhbmQgb2ZmIHRvIHRoZSAoc3R1YmJlZCkganVtcC1iYWxsIHJlc29sdmVyLjwvc3VtbWFy"
    "eT4KICAgIFJlc29sdmVKdW1wQmFsbAp9Cg=="
)
$f_src_Charm_Engine_EntryOutcomes_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_EntryOutcomes_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\EntryOutcomes.cs"), $f_src_Charm_Engine_EntryOutcomes_cs_bytes)
Write-Host "  wrote src/Charm.Engine/EntryOutcomes.cs"

# src/Charm.Engine/GameState.cs
$f_src_Charm_Engine_GameState_cs_b64 = @(
    "bmFtZXNwYWNlIENoYXJtLkVuZ2luZTsKCi8vLyA8c3VtbWFyeT5XaGljaCBzaWRlIGEgdGVhbSBp"
    "cyBvbi4gVXNlZCBieSB0aGUgcG9zc2Vzc2lvbiBhcnJvdyBhbmQsIGxhdGVyLAovLy8gYnkgc2Nv"
    "cmUvZm91bC90aW1lb3V0IHRyYWNraW5nLjwvc3VtbWFyeT4KcHVibGljIGVudW0gVGVhbVNpZGUK"
    "ewogICAgSG9tZSwKICAgIEF3YXkKfQoKLy8vIDxzdW1tYXJ5PgovLy8gUGVyc2lzdGVudCBnYW1l"
    "LXdpZGUgc3RhdGUgdGhhdCBzdXJ2aXZlcyBBQ1JPU1MgcG9zc2Vzc2lvbnMg4oCUIHVubGlrZQov"
    "Ly8gPHNlZSBjcmVmPSJQb3NzZXNzaW9uU3RhdGUiLz4sIHdoaWNoIGlzIHBlci1wb3NzZXNzaW9u"
    "LiBUaGlzIGlzIHdoZXJlIHRoZQovLy8gcG9zc2Vzc2lvbiBhcnJvdyBoYXMgdG8gbGl2ZSwgYmVj"
    "YXVzZSBhIGp1bXAgYmFsbCBpbiBvbmUgcG9zc2Vzc2lvbiBzZXRzIHdobwovLy8gZ2V0cyB0aGUg"
    "YmFsbCBpbiBhIGxhdGVyIG9uZS4KLy8vCi8vLyBTS0VMRVRPTiBPTkxZIHRoaXMgc2Vzc2lvbi4g"
    "VGhlIHBvc3Nlc3Npb24gYXJyb3cgaGFzIHJlYWwgYmVoYXZpb3IgKGl0Ci8vLyBmbGlwcykuIFNj"
    "b3JlLCBmb3VscywgYW5kIHRpbWVvdXRzIGFyZSBwbGFjZWhvbGRlciBmaWVsZHMg4oCUIHR5cGVk"
    "IGFuZCBuYW1lZAovLy8gc28gdGhlIHNoYXBlIGlzIGRlZmluZWQsIGJ1dCBOT1QgeWV0IHJlYWQg"
    "b3Igd3JpdHRlbiBkdXJpbmcgcG9zc2Vzc2lvbgovLy8gcmVzb2x1dGlvbi4gVGhleSBhcmUgZnV0"
    "dXJlIGluZnJhc3RydWN0dXJlLCBkZWxpYmVyYXRlbHkgaW5lcnQgZm9yIG5vdy4KLy8vIDwvc3Vt"
    "bWFyeT4KcHVibGljIHNlYWxlZCBjbGFzcyBHYW1lU3RhdGUKewogICAgLy8vIDxzdW1tYXJ5Pldo"
    "byBpcyBhd2FyZGVkIHRoZSBiYWxsIG9uIHRoZSBuZXh0IGFycm93LWRlY2lkZWQganVtcCBiYWxs"
    "Ljwvc3VtbWFyeT4KICAgIHB1YmxpYyBUZWFtU2lkZSBQb3NzZXNzaW9uQXJyb3cgeyBnZXQ7IHBy"
    "aXZhdGUgc2V0OyB9CgogICAgcHVibGljIEdhbWVTdGF0ZShUZWFtU2lkZSBpbml0aWFsQXJyb3cp"
    "ID0+IFBvc3Nlc3Npb25BcnJvdyA9IGluaXRpYWxBcnJvdzsKCiAgICAvLy8gPHN1bW1hcnk+Rmxp"
    "cCB0aGUgYXJyb3cgdG8gdGhlIG90aGVyIHRlYW0uIEEgZnV0dXJlIGp1bXAtYmFsbCByZXNvbHZl"
    "cgogICAgLy8vIGNhbGxzIHRoaXMgd2hlbiB0aGUgYXJyb3cgaXMgY29uc3VtZWQ7IG5vdGhpbmcg"
    "aW4gUm9sbCBBIHRvdWNoZXMgaXQuPC9zdW1tYXJ5PgogICAgcHVibGljIHZvaWQgRmxpcFBvc3Nl"
    "c3Npb25BcnJvdygpID0+CiAgICAgICAgUG9zc2Vzc2lvbkFycm93ID0gUG9zc2Vzc2lvbkFycm93"
    "ID09IFRlYW1TaWRlLkhvbWUgPyBUZWFtU2lkZS5Bd2F5IDogVGVhbVNpZGUuSG9tZTsKCiAgICAv"
    "LyAtLS0gUGxhY2Vob2xkZXIgZmllbGRzOiBkZWZpbmVkIHNoYXBlLCBub3QgeWV0IHdpcmVkIHRv"
    "IGFueXRoaW5nLiAtLS0KICAgIHB1YmxpYyBpbnQgSG9tZVNjb3JlIHsgZ2V0OyBzZXQ7IH0KICAg"
    "IHB1YmxpYyBpbnQgQXdheVNjb3JlIHsgZ2V0OyBzZXQ7IH0KICAgIHB1YmxpYyBpbnQgSG9tZVRl"
    "YW1Gb3VscyB7IGdldDsgc2V0OyB9CiAgICBwdWJsaWMgaW50IEF3YXlUZWFtRm91bHMgeyBnZXQ7"
    "IHNldDsgfQogICAgcHVibGljIGludCBIb21lVGltZW91dHMgeyBnZXQ7IHNldDsgfQogICAgcHVi"
    "bGljIGludCBBd2F5VGltZW91dHMgeyBnZXQ7IHNldDsgfQp9Cg=="
)
$f_src_Charm_Engine_GameState_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_GameState_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\GameState.cs"), $f_src_Charm_Engine_GameState_cs_bytes)
Write-Host "  wrote src/Charm.Engine/GameState.cs"

# src/Charm.Engine/RollA.cs
$f_src_Charm_Engine_RollA_cs_b64 = @(
    "bmFtZXNwYWNlIENoYXJtLkVuZ2luZTsKCi8vLyA8c3VtbWFyeT4KLy8vIFJvbGwgQSDigJQgRW50"
    "cnk6IEluYm91bmRzIChEZWFkIEJhbGwpLiBUaGUgZmlyc3Qgbm9kZSBvZiB0aGUgZW5naW5lIGFu"
    "ZCB0aGUKLy8vIHRlbXBsYXRlIGV2ZXJ5IGxhdGVyIHJvbGwgZm9sbG93czogcmVjZWl2ZSBzdGF0"
    "ZSArIGEgZmluaXNoZWQgcGllLCByb2xsCi8vLyBhZ2FpbnN0IHRoZSBwaWUsIHJldHVybiBleGFj"
    "dGx5IG9uZSB0eXBlZCByZXN1bHQsIG5hbWUgbm8gc3VjY2Vzc29yLgovLy8gPC9zdW1tYXJ5Pgpw"
    "dWJsaWMgc3RhdGljIGNsYXNzIFJvbGxBCnsKICAgIHB1YmxpYyBzdGF0aWMgUm9sbFJlc3VsdCBF"
    "eGVjdXRlKFBvc3Nlc3Npb25TdGF0ZSBzdGF0ZSwgUGllPEVudHJ5T3V0Y29tZT4gcGllLCBJUm5n"
    "IHJuZywgUm9sbEFDb25maWcgY2ZnKQogICAgewogICAgICAgIC8vIFRoZSBwaWUgaXMgdmFsaWQg"
    "YnkgY29uc3RydWN0aW9uIChzZWUgUGllJmx0O1QmZ3Q7KSwgc28gcmVjZWl2aW5nIGl0IGlzCiAg"
    "ICAgICAgLy8gYWxyZWFkeSB0aGUgInZhbGlkYXRlIG9uIHJlY2VpcHQiIGd1YXJhbnRlZSDigJQg"
    "YW4gaW52YWxpZCBwaWUgY291bGQgbm90CiAgICAgICAgLy8gaGF2ZSBiZWVuIGJ1aWx0IGFuZCBo"
    "YW5kZWQgaGVyZS4KICAgICAgICB2YXIgZHJhdyA9IHJuZy5OZXh0VW5pdEludGVydmFsKCk7CiAg"
    "ICAgICAgdmFyIG91dGNvbWUgPSBwaWUuUm9sbChkcmF3KTsKCiAgICAgICAgcmV0dXJuIG91dGNv"
    "bWUgc3dpdGNoCiAgICAgICAgewogICAgICAgICAgICAvLyBDbGVhbiBlbnRyeSAtPiBDT05USU5V"
    "RS4gVGhlIGhhbGZjb3VydCBzZXQgaXMgb3BhcXVlIHRvIFJvbGwgQS4KICAgICAgICAgICAgRW50"
    "cnlPdXRjb21lLkNsZWFuRW50cnkgPT4KICAgICAgICAgICAgICAgIG5ldyBDb250aW51ZShDb250"
    "aW51YXRpb25LaW5kLkludG9IYWxmY291cnRTZXQsIHN0YXRlKSwKCiAgICAgICAgICAgIC8vIFR1"
    "cm5vdmVyIC0+IENPTlRJTlVFLiBUaGUgdHVybm92ZXItdHlwZSByZXNvbHZlciBpcyBvcGFxdWUg"
    "dG8gUm9sbCBBLgogICAgICAgICAgICBFbnRyeU91dGNvbWUuVHVybm92ZXIgPT4KICAgICAgICAg"
    "ICAgICAgIG5ldyBDb250aW51ZShDb250aW51YXRpb25LaW5kLlJlc29sdmVUdXJub3ZlclR5cGUs"
    "IHN0YXRlKSwKCiAgICAgICAgICAgIC8vIFNob3QtY2xvY2sgdmlvbGF0aW9uIC0+IFRFUk1JTkFM"
    "LiBFbGFwc2VkIHRpbWUgaXMgaW52YXJpYW50IChmdWxsCiAgICAgICAgICAgIC8vIGNsb2NrKSwg"
    "c28gaXQgaXMgc3RhbXBlZCBoZXJlIGFuZCBuZWVkcyBubyBzZXBhcmF0ZSB0aW1lIHJvbGwuCiAg"
    "ICAgICAgICAgIEVudHJ5T3V0Y29tZS5TaG90Q2xvY2tWaW9sYXRpb24gPT4KICAgICAgICAgICAg"
    "ICAgIG5ldyBUZXJtaW5hbCgiU2hvdENsb2NrVmlvbGF0aW9uIiwgc3RhdGUpIHsgRWxhcHNlZFNl"
    "Y29uZHMgPSBjZmcuVmlvbGF0aW9uRWxhcHNlZFNlY29uZHMgfSwKCiAgICAgICAgICAgIC8vIEZv"
    "dWwgLT4gQ09OVElOVUUuIEEgZnV0dXJlIGZvdWwtdHlwZSByZXNvbHZlciBkZWNpZGVzIGRlZmVu"
    "c2l2ZSB2cy4KICAgICAgICAgICAgLy8gb2ZmZW5zaXZlIGFuZCB3aGF0IGl0IHRyaWdnZXJzLiBS"
    "ZWFsIHZhcmlhbmNlLCBuZXZlciByZXNvbHZlZCBoZXJlLgogICAgICAgICAgICBFbnRyeU91dGNv"
    "bWUuRm91bCA9PgogICAgICAgICAgICAgICAgbmV3IENvbnRpbnVlKENvbnRpbnVhdGlvbktpbmQu"
    "UmVzb2x2ZUZvdWxUeXBlLCBzdGF0ZSksCgogICAgICAgICAgICAvLyBKdW1wIGJhbGwgLT4gQ09O"
    "VElOVUUuIEEgZnV0dXJlIGp1bXAtYmFsbCByZXNvbHZlciBjb25zdWx0cyB0aGUKICAgICAgICAg"
    "ICAgLy8gcG9zc2Vzc2lvbiBhcnJvdyBvbiBHYW1lU3RhdGUuCiAgICAgICAgICAgIEVudHJ5T3V0"
    "Y29tZS5KdW1wQmFsbCA9PgogICAgICAgICAgICAgICAgbmV3IENvbnRpbnVlKENvbnRpbnVhdGlv"
    "bktpbmQuUmVzb2x2ZUp1bXBCYWxsLCBzdGF0ZSksCgogICAgICAgICAgICBfID0+IHRocm93IG5l"
    "dyBJbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uKCQiVW5oYW5kbGVkIGVudHJ5IG91dGNvbWUgJ3tv"
    "dXRjb21lfScuIikKICAgICAgICB9OwogICAgfQp9Cg=="
)
$f_src_Charm_Engine_RollA_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_RollA_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\RollA.cs"), $f_src_Charm_Engine_RollA_cs_bytes)
Write-Host "  wrote src/Charm.Engine/RollA.cs"

# src/Charm.Engine/Resolver.cs
$f_src_Charm_Engine_Resolver_cs_b64 = @(
    "bmFtZXNwYWNlIENoYXJtLkVuZ2luZTsKCi8vLyA8c3VtbWFyeT5XaGF0IHRoZSByZXNvbHZlciBk"
    "aWQgd2l0aCBvbmUgcmVzdWx0IOKAlCBmb3Igb2JzZXJ2YWJpbGl0eS9oYXJuZXNzLjwvc3VtbWFy"
    "eT4KcHVibGljIHJlYWRvbmx5IHJlY29yZCBzdHJ1Y3QgUm91dGluZ091dGNvbWUoYm9vbCBQb3Nz"
    "ZXNzaW9uRW5kZWQsIHN0cmluZyBEZXN0aW5hdGlvbik7CgovLy8gPHN1bW1hcnk+Ci8vLyBUaGUg"
    "dGhpbmcgdGhhdCB3YWxrcyB0aGUgY2hhaW4uIEl0IG93bnMgYWxsIHJvdXRpbmc6IGEgVGVybWlu"
    "YWwgZW5kcyB0aGUKLy8vIHBvc3Nlc3Npb247IGEgQ29udGludWUgaXMgbWFwcGVkIOKAlCBieSBp"
    "dHMgPHNlZSBjcmVmPSJDb250aW51YXRpb25LaW5kIi8+LCB0aGUKLy8vIG9ubHkgcGxhY2UgdGhh"
    "dCBtYXBwaW5nIGxpdmVzIOKAlCB0byB0aGUgbmV4dCBub2RlLiBXaGVuIHJlYWwgbm9kZXMgcmVw"
    "bGFjZSB0aGUKLy8vIHN0dWJzLCBvbmx5IHRoaXMgbWFwcGluZyBjaGFuZ2VzOyB0aGUgcm9sbHMg"
    "dGhhdCBlbWl0IHJlc3VsdHMgbmV2ZXIgcmVvcGVuLgovLy8gPC9zdW1tYXJ5PgpwdWJsaWMgc2Vh"
    "bGVkIGNsYXNzIFJlc29sdmVyCnsKICAgIHByaXZhdGUgcmVhZG9ubHkgSUNvbnRpbnVhdGlvbk5v"
    "ZGUgX2ludG9IYWxmY291cnRTZXQ7CiAgICBwcml2YXRlIHJlYWRvbmx5IElDb250aW51YXRpb25O"
    "b2RlIF9yZXNvbHZlVHVybm92ZXJUeXBlOwogICAgcHJpdmF0ZSByZWFkb25seSBJQ29udGludWF0"
    "aW9uTm9kZSBfcmVzb2x2ZUZvdWxUeXBlOwogICAgcHJpdmF0ZSByZWFkb25seSBJQ29udGludWF0"
    "aW9uTm9kZSBfcmVzb2x2ZUp1bXBCYWxsOwoKICAgIHB1YmxpYyBSZXNvbHZlcigKICAgICAgICBJ"
    "Q29udGludWF0aW9uTm9kZSBpbnRvSGFsZmNvdXJ0U2V0LAogICAgICAgIElDb250aW51YXRpb25O"
    "b2RlIHJlc29sdmVUdXJub3ZlclR5cGUsCiAgICAgICAgSUNvbnRpbnVhdGlvbk5vZGUgcmVzb2x2"
    "ZUZvdWxUeXBlLAogICAgICAgIElDb250aW51YXRpb25Ob2RlIHJlc29sdmVKdW1wQmFsbCkKICAg"
    "IHsKICAgICAgICBfaW50b0hhbGZjb3VydFNldCA9IGludG9IYWxmY291cnRTZXQ7CiAgICAgICAg"
    "X3Jlc29sdmVUdXJub3ZlclR5cGUgPSByZXNvbHZlVHVybm92ZXJUeXBlOwogICAgICAgIF9yZXNv"
    "bHZlRm91bFR5cGUgPSByZXNvbHZlRm91bFR5cGU7CiAgICAgICAgX3Jlc29sdmVKdW1wQmFsbCA9"
    "IHJlc29sdmVKdW1wQmFsbDsKICAgIH0KCiAgICBwdWJsaWMgUm91dGluZ091dGNvbWUgUm91dGUo"
    "Um9sbFJlc3VsdCByZXN1bHQpID0+IHJlc3VsdCBzd2l0Y2gKICAgIHsKICAgICAgICBUZXJtaW5h"
    "bCB0ID0+IG5ldyBSb3V0aW5nT3V0Y29tZShQb3NzZXNzaW9uRW5kZWQ6IHRydWUsIERlc3RpbmF0"
    "aW9uOiAkIkVORDp7dC5SZWFzb259IiksCgogICAgICAgIENvbnRpbnVlIGMgPT4gYy5OZXh0IHN3"
    "aXRjaAogICAgICAgIHsKICAgICAgICAgICAgQ29udGludWF0aW9uS2luZC5JbnRvSGFsZmNvdXJ0"
    "U2V0ID0+CiAgICAgICAgICAgICAgICBuZXcgUm91dGluZ091dGNvbWUoZmFsc2UsIF9pbnRvSGFs"
    "ZmNvdXJ0U2V0LlJlY2VpdmUoYykpLAogICAgICAgICAgICBDb250aW51YXRpb25LaW5kLlJlc29s"
    "dmVUdXJub3ZlclR5cGUgPT4KICAgICAgICAgICAgICAgIG5ldyBSb3V0aW5nT3V0Y29tZShmYWxz"
    "ZSwgX3Jlc29sdmVUdXJub3ZlclR5cGUuUmVjZWl2ZShjKSksCiAgICAgICAgICAgIENvbnRpbnVh"
    "dGlvbktpbmQuUmVzb2x2ZUZvdWxUeXBlID0+CiAgICAgICAgICAgICAgICBuZXcgUm91dGluZ091"
    "dGNvbWUoZmFsc2UsIF9yZXNvbHZlRm91bFR5cGUuUmVjZWl2ZShjKSksCiAgICAgICAgICAgIENv"
    "bnRpbnVhdGlvbktpbmQuUmVzb2x2ZUp1bXBCYWxsID0+CiAgICAgICAgICAgICAgICBuZXcgUm91"
    "dGluZ091dGNvbWUoZmFsc2UsIF9yZXNvbHZlSnVtcEJhbGwuUmVjZWl2ZShjKSksCiAgICAgICAg"
    "ICAgIF8gPT4gdGhyb3cgbmV3IEludmFsaWRPcGVyYXRpb25FeGNlcHRpb24oJCJObyByb3V0ZSBm"
    "b3IgY29udGludWF0aW9uICd7Yy5OZXh0fScuIikKICAgICAgICB9LAoKICAgICAgICBfID0+IHRo"
    "cm93IG5ldyBJbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uKCQiVW5rbm93biByZXN1bHQgdHlwZSAn"
    "e3Jlc3VsdC5HZXRUeXBlKCkuTmFtZX0nLiIpCiAgICB9Owp9Cg=="
)
$f_src_Charm_Engine_Resolver_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_Resolver_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\Resolver.cs"), $f_src_Charm_Engine_Resolver_cs_bytes)
Write-Host "  wrote src/Charm.Engine/Resolver.cs"

# src/Charm.Engine/StubPieGenerator.cs
$f_src_Charm_Engine_StubPieGenerator_cs_b64 = @(
    "bmFtZXNwYWNlIENoYXJtLkVuZ2luZTsKCi8vLyA8c3VtbWFyeT4KLy8vIFNUVUIuIE5vdCB0aGUg"
    "cmVhbCBhdHRyaWJ1dGUtZHJpdmVuIHBpZSBnZW5lcmF0b3IuIEl0IGV4aXN0cyBvbmx5IHNvIFJv"
    "bGwgQQovLy8gaGFzIGEgdmFsaWQgcGllIHRvIGNvbnN1bWUgYW5kIHNvIHdlIGNhbiBwcm92ZSB0"
    "aGUgZ2VuZXJhdG9yLT5yb2xsIHNlYW0KLy8vIGNhcnJpZXMgc2lnbmFsLiBUaGUgcmVhbCBnZW5l"
    "cmF0b3IgKGF0dHJpYnV0ZXMgLT4gbWF0Y2h1cCAtPiB3ZWlnaHRlZCBvZGRzKQovLy8gaXMgb3V0"
    "IG9mIHNjb3BlIGFuZCB3aWxsIHJlcGxhY2UgdGhpcyB3aXRob3V0IGNoYW5naW5nIFJvbGwgQS4K"
    "Ly8vIDwvc3VtbWFyeT4KcHVibGljIHNlYWxlZCBjbGFzcyBTdHViUGllR2VuZXJhdG9yCnsKICAg"
    "IHByaXZhdGUgcmVhZG9ubHkgUm9sbEFDb25maWcgX2NmZzsKCiAgICBwdWJsaWMgU3R1YlBpZUdl"
    "bmVyYXRvcihSb2xsQUNvbmZpZyBjZmcpID0+IF9jZmcgPSBjZmc7CgogICAgLy8vIDxwYXJhbSBu"
    "YW1lPSJzdGF0ZSI+Q3VycmVudCBwb3NzZXNzaW9uICh1bnVzZWQgYnkgdGhlIHN0dWI7IHRoZSBy"
    "ZWFsCiAgICAvLy8gZ2VuZXJhdG9yIHdpbGwgcmVhZCBhdHRyaWJ1dGVzIG9mZiBpdCkuPC9wYXJh"
    "bT4KICAgIC8vLyA8cGFyYW0gbmFtZT0icHJlc3N1cmUiPkEgc2luZ2xlIDAuLjEgc2NhbGFyIHN0"
    "YW5kaW5nIGluIGZvciAiZGVmZW5zaXZlCiAgICAvLy8gcHJlc3N1cmUiLiBUaGUgb25lIGxpdmUg"
    "aW5wdXQsIHdpcmVkIHRvIGEgdHJpdmlhbCBudWRnZSBvbiB0aGUgdHVybm92ZXIKICAgIC8vLyBz"
    "bGljZSDigJQgYSBwbGFjZWhvbGRlciB0byBwcm92ZSB0aGUgd2lyZSBtb3ZlcyBvdXRjb21lcywg"
    "bm90IHJlYWwgbG9naWMuPC9wYXJhbT4KICAgIHB1YmxpYyBQaWU8RW50cnlPdXRjb21lPiBHZW5l"
    "cmF0ZShQb3NzZXNzaW9uU3RhdGUgc3RhdGUsIGRvdWJsZSBwcmVzc3VyZSkKICAgIHsKICAgICAg"
    "ICBpZiAocHJlc3N1cmUgPCAwIHx8IHByZXNzdXJlID4gMSkKICAgICAgICAgICAgdGhyb3cgbmV3"
    "IEFyZ3VtZW50T3V0T2ZSYW5nZUV4Y2VwdGlvbihuYW1lb2YocHJlc3N1cmUpLCBwcmVzc3VyZSwg"
    "IlByZXNzdXJlIG11c3QgYmUgaW4gWzAsIDFdLiIpOwoKICAgICAgICAvLyBUaGUgc2luZ2xlIGxp"
    "dmUgd2lyZTogcHJlc3N1cmUgbnVkZ2VzIHR1cm5vdmVyIHVwLiBFdmVyeXRoaW5nIGVsc2UgaXMK"
    "ICAgICAgICAvLyB0aGUgY29uZmlndXJlZCBiYXNlLiBUaGVuIHJlbm9ybWFsaXplIHNvIHRoZSBz"
    "bGljZXMgc3VtIHRvIDEuCiAgICAgICAgdmFyIGNsZWFuID0gX2NmZy5CYXNlQ2xlYW47CiAgICAg"
    "ICAgdmFyIHR1cm5vdmVyID0gX2NmZy5CYXNlVHVybm92ZXIgKyBwcmVzc3VyZSAqIF9jZmcuUHJl"
    "c3N1cmVUdXJub3Zlck51ZGdlOwogICAgICAgIHZhciB2aW9sYXRpb24gPSBfY2ZnLkJhc2VWaW9s"
    "YXRpb247CiAgICAgICAgdmFyIGZvdWwgPSBfY2ZnLkJhc2VGb3VsOwogICAgICAgIHZhciBqdW1w"
    "QmFsbCA9IF9jZmcuQmFzZUp1bXBCYWxsOwoKICAgICAgICB2YXIgdG90YWwgPSBjbGVhbiArIHR1"
    "cm5vdmVyICsgdmlvbGF0aW9uICsgZm91bCArIGp1bXBCYWxsOwogICAgICAgIHZhciB3ZWlnaHRz"
    "ID0gbmV3IERpY3Rpb25hcnk8RW50cnlPdXRjb21lLCBkb3VibGU+CiAgICAgICAgewogICAgICAg"
    "ICAgICBbRW50cnlPdXRjb21lLkNsZWFuRW50cnldID0gY2xlYW4gLyB0b3RhbCwKICAgICAgICAg"
    "ICAgW0VudHJ5T3V0Y29tZS5UdXJub3Zlcl0gPSB0dXJub3ZlciAvIHRvdGFsLAogICAgICAgICAg"
    "ICBbRW50cnlPdXRjb21lLlNob3RDbG9ja1Zpb2xhdGlvbl0gPSB2aW9sYXRpb24gLyB0b3RhbCwK"
    "ICAgICAgICAgICAgW0VudHJ5T3V0Y29tZS5Gb3VsXSA9IGZvdWwgLyB0b3RhbCwKICAgICAgICAg"
    "ICAgW0VudHJ5T3V0Y29tZS5KdW1wQmFsbF0gPSBqdW1wQmFsbCAvIHRvdGFsLAogICAgICAgIH07"
    "CgogICAgICAgIHJldHVybiBuZXcgUGllPEVudHJ5T3V0Y29tZT4od2VpZ2h0cywgX2NmZy5FcHNp"
    "bG9uKTsKICAgIH0KfQo="
)
$f_src_Charm_Engine_StubPieGenerator_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_StubPieGenerator_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\StubPieGenerator.cs"), $f_src_Charm_Engine_StubPieGenerator_cs_bytes)
Write-Host "  wrote src/Charm.Engine/StubPieGenerator.cs"

# src/Charm.Engine/Stubs.cs
$f_src_Charm_Engine_Stubs_cs_b64 = @(
    "bmFtZXNwYWNlIENoYXJtLkVuZ2luZTsKCi8vLyA8c3VtbWFyeT4KLy8vIFNUVUJTIGZvciB0aGUg"
    "bm9kZXMgYSBDT05USU5VRSByb3V0ZXMgdG8uIFRoZXkgY29udGFpbiBubyBiYXNrZXRiYWxsIGxv"
    "Z2ljIOKAlAovLy8gZWFjaCBvbmx5IHJlY29yZHMgdGhhdCBpdCByZWNlaXZlZCBhIGNsZWFuIGhh"
    "bmQtb2ZmLCBzbyB0aGUgYmF0Y2ggaGFybmVzcyBjYW4KLy8vIGNvbmZpcm0gZXZlcnkgY29udGlu"
    "dWUgbGFuZHMgc29tZXdoZXJlLiBUaGV5IHdpbGwgYmUgcmVwbGFjZWQgYnkgcmVhbCBub2Rlcwov"
    "Ly8gd2l0aG91dCBSb2xsIEEgb3IgdGhlIHJlc3VsdCBjb250cmFjdCBjaGFuZ2luZy4KLy8vIDwv"
    "c3VtbWFyeT4KcHVibGljIGludGVyZmFjZSBJQ29udGludWF0aW9uTm9kZQp7CiAgICAvLy8gPHN1"
    "bW1hcnk+UmVjZWl2ZSBhIHJvdXRlZCBjb250aW51YXRpb24uIFJldHVybnMgYSBsYWJlbCBmb3Ig"
    "b2JzZXJ2YWJpbGl0eS48L3N1bW1hcnk+CiAgICBzdHJpbmcgUmVjZWl2ZShDb250aW51ZSBjb250"
    "aW51YXRpb24pOwp9CgovLy8gPHN1bW1hcnk+U1RVQiBmb3IgdGhlIGhhbGZjb3VydC1zZXQgbm9k"
    "ZSAodGhlIG9wYXF1ZSAibmV4dCIgbm9kZSkuPC9zdW1tYXJ5PgpwdWJsaWMgc2VhbGVkIGNsYXNz"
    "IEhhbGZjb3VydFNldFN0dWIgOiBJQ29udGludWF0aW9uTm9kZQp7CiAgICBwdWJsaWMgc3RyaW5n"
    "IFJlY2VpdmUoQ29udGludWUgY29udGludWF0aW9uKSA9PiAiU1RVQjpIYWxmY291cnRTZXQiOwp9"
    "CgovLy8gPHN1bW1hcnk+U1RVQiBmb3IgdGhlIHR1cm5vdmVyLXR5cGUgcmVzb2x2ZXIuPC9zdW1t"
    "YXJ5PgpwdWJsaWMgc2VhbGVkIGNsYXNzIFR1cm5vdmVyVHlwZVJlc29sdmVyU3R1YiA6IElDb250"
    "aW51YXRpb25Ob2RlCnsKICAgIHB1YmxpYyBzdHJpbmcgUmVjZWl2ZShDb250aW51ZSBjb250aW51"
    "YXRpb24pID0+ICJTVFVCOlR1cm5vdmVyVHlwZVJlc29sdmVyIjsKfQoKLy8vIDxzdW1tYXJ5PlNU"
    "VUIgZm9yIHRoZSBmb3VsLXR5cGUgcmVzb2x2ZXIgKGRlZmVuc2l2ZSBub24tc2hvb3RpbmcgdnMu"
    "IG9mZmVuc2l2ZSkuPC9zdW1tYXJ5PgpwdWJsaWMgc2VhbGVkIGNsYXNzIEZvdWxUeXBlUmVzb2x2"
    "ZXJTdHViIDogSUNvbnRpbnVhdGlvbk5vZGUKewogICAgcHVibGljIHN0cmluZyBSZWNlaXZlKENv"
    "bnRpbnVlIGNvbnRpbnVhdGlvbikgPT4gIlNUVUI6Rm91bFR5cGVSZXNvbHZlciI7Cn0KCi8vLyA8"
    "c3VtbWFyeT5TVFVCIGZvciB0aGUganVtcC1iYWxsIHJlc29sdmVyIChjb25zdWx0cyB0aGUgcG9z"
    "c2Vzc2lvbiBhcnJvdykuPC9zdW1tYXJ5PgpwdWJsaWMgc2VhbGVkIGNsYXNzIEp1bXBCYWxsUmVz"
    "b2x2ZXJTdHViIDogSUNvbnRpbnVhdGlvbk5vZGUKewogICAgcHVibGljIHN0cmluZyBSZWNlaXZl"
    "KENvbnRpbnVlIGNvbnRpbnVhdGlvbikgPT4gIlNUVUI6SnVtcEJhbGxSZXNvbHZlciI7Cn0K"
)
$f_src_Charm_Engine_Stubs_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Engine_Stubs_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Engine\Stubs.cs"), $f_src_Charm_Engine_Stubs_cs_bytes)
Write-Host "  wrote src/Charm.Engine/Stubs.cs"

# src/Charm.Harness/Charm.Harness.csproj
$f_src_Charm_Harness_Charm_Harness_csproj_b64 = @(
    "PFByb2plY3QgU2RrPSJNaWNyb3NvZnQuTkVULlNkayI+CgogIDxQcm9wZXJ0eUdyb3VwPgogICAg"
    "PE91dHB1dFR5cGU+RXhlPC9PdXRwdXRUeXBlPgogICAgPFRhcmdldEZyYW1ld29yaz5uZXQxMC4w"
    "PC9UYXJnZXRGcmFtZXdvcms+CiAgICA8SW1wbGljaXRVc2luZ3M+ZW5hYmxlPC9JbXBsaWNpdFVz"
    "aW5ncz4KICAgIDxOdWxsYWJsZT5lbmFibGU8L051bGxhYmxlPgogICAgPFJvb3ROYW1lc3BhY2U+"
    "Q2hhcm0uSGFybmVzczwvUm9vdE5hbWVzcGFjZT4KICA8L1Byb3BlcnR5R3JvdXA+CgogIDxJdGVt"
    "R3JvdXA+CiAgICA8UHJvamVjdFJlZmVyZW5jZSBJbmNsdWRlPSIuLlxDaGFybS5FbmdpbmVcQ2hh"
    "cm0uRW5naW5lLmNzcHJvaiIgLz4KICA8L0l0ZW1Hcm91cD4KCiAgPEl0ZW1Hcm91cD4KICAgIDxO"
    "b25lIFVwZGF0ZT0iY29uZmlnLmpzb24iPgogICAgICA8Q29weVRvT3V0cHV0RGlyZWN0b3J5PlBy"
    "ZXNlcnZlTmV3ZXN0PC9Db3B5VG9PdXRwdXREaXJlY3Rvcnk+CiAgICA8L05vbmU+CiAgPC9JdGVt"
    "R3JvdXA+Cgo8L1Byb2plY3Q+Cg=="
)
$f_src_Charm_Harness_Charm_Harness_csproj_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Harness_Charm_Harness_csproj_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Harness\Charm.Harness.csproj"), $f_src_Charm_Harness_Charm_Harness_csproj_bytes)
Write-Host "  wrote src/Charm.Harness/Charm.Harness.csproj"

# src/Charm.Harness/Program.cs
$f_src_Charm_Harness_Program_cs_b64 = @(
    "dXNpbmcgQ2hhcm0uRW5naW5lOwoKbmFtZXNwYWNlIENoYXJtLkhhcm5lc3M7CgppbnRlcm5hbCBz"
    "dGF0aWMgY2xhc3MgUHJvZ3JhbQp7CiAgICBwcml2YXRlIHN0YXRpYyBpbnQgTWFpbigpCiAgICB7"
    "CiAgICAgICAgdmFyIGNvbmZpZ1BhdGggPSBQYXRoLkNvbWJpbmUoQXBwQ29udGV4dC5CYXNlRGly"
    "ZWN0b3J5LCAiY29uZmlnLmpzb24iKTsKICAgICAgICB2YXIgY2ZnID0gUm9sbEFDb25maWcuTG9h"
    "ZChjb25maWdQYXRoKTsKCiAgICAgICAgdmFyIGdlbmVyYXRvciA9IG5ldyBTdHViUGllR2VuZXJh"
    "dG9yKGNmZyk7CiAgICAgICAgdmFyIHJlc29sdmVyID0gbmV3IFJlc29sdmVyKAogICAgICAgICAg"
    "ICBuZXcgSGFsZmNvdXJ0U2V0U3R1YigpLAogICAgICAgICAgICBuZXcgVHVybm92ZXJUeXBlUmVz"
    "b2x2ZXJTdHViKCksCiAgICAgICAgICAgIG5ldyBGb3VsVHlwZVJlc29sdmVyU3R1YigpLAogICAg"
    "ICAgICAgICBuZXcgSnVtcEJhbGxSZXNvbHZlclN0dWIoKSk7CiAgICAgICAgdmFyIHN0YXRlID0g"
    "bmV3IFBvc3Nlc3Npb25TdGF0ZShQb3NzZXNzaW9uTnVtYmVyOiAxLCBPZmZlbnNlOiAiSE9NRSIs"
    "IERlZmVuc2U6ICJBV0FZIiwgRW50cnk6IEVudHJ5VHlwZS5EZWFkQmFsbEluYm91bmQpOwoKICAg"
    "ICAgICBDb25zb2xlLldyaXRlTGluZSgiPT09IFByb2plY3QgQ2hhcm0gOjogUm9sbCBBIOKAlCBF"
    "bnRyeTogSW5ib3VuZHMgKERlYWQgQmFsbCkgPT09XG4iKTsKCiAgICAgICAgU2hvd0dhbWVTdGF0"
    "ZVNrZWxldG9uKCk7CiAgICAgICAgU2hvd1NhbXBsZXMoY2ZnLCBnZW5lcmF0b3IsIHJlc29sdmVy"
    "LCBzdGF0ZSk7CiAgICAgICAgdmFyIG9rID0gQmF0Y2hDaGVjayhjZmcsIGdlbmVyYXRvciwgcmVz"
    "b2x2ZXIsIHN0YXRlKTsKICAgICAgICBvayAmPSBQcmVzc3VyZVNpZ25hbENoZWNrKGNmZywgZ2Vu"
    "ZXJhdG9yLCBzdGF0ZSk7CgogICAgICAgIENvbnNvbGUuV3JpdGVMaW5lKG9rID8gIlxuQUxMIENI"
    "RUNLUyBQQVNTRUQuIiA6ICJcbkNIRUNLUyBGQUlMRUQuIik7CiAgICAgICAgcmV0dXJuIG9rID8g"
    "MCA6IDE7CiAgICB9CgogICAgLy8gLS0tIEdhbWVTdGF0ZSBza2VsZXRvbjogcHJvdmUgdGhlIHBl"
    "cnNpc3RlbnQgYXJyb3cgZXhpc3RzIGFuZCBmbGlwcy4gLS0tCiAgICBwcml2YXRlIHN0YXRpYyB2"
    "b2lkIFNob3dHYW1lU3RhdGVTa2VsZXRvbigpCiAgICB7CiAgICAgICAgQ29uc29sZS5Xcml0ZUxp"
    "bmUoIi0tLSBHYW1lU3RhdGUgc2tlbGV0b24gKHBlcnNpc3RlbnQgYWNyb3NzIHBvc3Nlc3Npb25z"
    "KSAtLS0iKTsKICAgICAgICB2YXIgZ2FtZSA9IG5ldyBHYW1lU3RhdGUoVGVhbVNpZGUuSG9tZSk7"
    "CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoJCIgIHBvc3Nlc3Npb24gYXJyb3cgc3RhcnRzOiB7"
    "Z2FtZS5Qb3NzZXNzaW9uQXJyb3d9Iik7CiAgICAgICAgZ2FtZS5GbGlwUG9zc2Vzc2lvbkFycm93"
    "KCk7CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoJCIgIGFmdGVyIGEgZmxpcDogICAgICAgICAg"
    "ICB7Z2FtZS5Qb3NzZXNzaW9uQXJyb3d9Iik7CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoIiAg"
    "KHNjb3JlL2ZvdWxzL3RpbWVvdXRzIGV4aXN0IGFzIHBsYWNlaG9sZGVyIGZpZWxkcywgbm90IHll"
    "dCB3aXJlZClcbiIpOwogICAgfQoKICAgIC8vIC0tLSBPYnNlcnZhYmlsaXR5OiBwcmludCBhIGZl"
    "dyBwaWVzIHdpdGggdGhlaXIgaW5wdXRzIGFuZCBvdXRjb21lcy4gLS0tCiAgICBwcml2YXRlIHN0"
    "YXRpYyB2b2lkIFNob3dTYW1wbGVzKFJvbGxBQ29uZmlnIGNmZywgU3R1YlBpZUdlbmVyYXRvciBn"
    "ZW4sIFJlc29sdmVyIHJlc29sdmVyLCBQb3NzZXNzaW9uU3RhdGUgc3RhdGUpCiAgICB7CiAgICAg"
    "ICAgQ29uc29sZS5Xcml0ZUxpbmUoIi0tLSBPYnNlcnZhYmlsaXR5OiBzYW1wbGUgcG9zc2Vzc2lv"
    "bnMgKHNlZWRlZCkgLS0tIik7CiAgICAgICAgdmFyIHJuZyA9IG5ldyBTeXN0ZW1SbmcoY2ZnLlNl"
    "ZWQpOwogICAgICAgIGNvbnN0IGRvdWJsZSBwcmVzc3VyZSA9IDAuNTsKCiAgICAgICAgZm9yICh2"
    "YXIgaSA9IDA7IGkgPCA4OyBpKyspCiAgICAgICAgewogICAgICAgICAgICB2YXIgcGllID0gZ2Vu"
    "LkdlbmVyYXRlKHN0YXRlLCBwcmVzc3VyZSk7CiAgICAgICAgICAgIHZhciByZXN1bHQgPSBSb2xs"
    "QS5FeGVjdXRlKHN0YXRlLCBwaWUsIHJuZywgY2ZnKTsKICAgICAgICAgICAgdmFyIHJvdXRpbmcg"
    "PSByZXNvbHZlci5Sb3V0ZShyZXN1bHQpOwoKICAgICAgICAgICAgdmFyIGtpbmQgPSByZXN1bHQg"
    "aXMgVGVybWluYWwgPyAiVEVSTUlOQUwiIDogIkNPTlRJTlVFIjsKICAgICAgICAgICAgdmFyIGVs"
    "YXBzZWQgPSByZXN1bHQuRWxhcHNlZFNlY29uZHMgaXMgeyB9IHMgPyAkIntzOjB9cyIgOiAiZGVm"
    "ZXJyZWQiOwogICAgICAgICAgICBDb25zb2xlLldyaXRlTGluZSgKICAgICAgICAgICAgICAgICQi"
    "ICByZXN1bHQ9e2tpbmQsLTh9IHwgZWxhcHNlZD17ZWxhcHNlZCwtOH0gfCByb3V0ZSAtPiB7cm91"
    "dGluZy5EZXN0aW5hdGlvbn0iICsKICAgICAgICAgICAgICAgIChyb3V0aW5nLlBvc3Nlc3Npb25F"
    "bmRlZCA/ICIgKHBvc3Nlc3Npb24gZW5kZWQpIiA6ICIiKSk7CiAgICAgICAgfQogICAgICAgIENv"
    "bnNvbGUuV3JpdGVMaW5lKCk7CiAgICB9CgogICAgLy8gLS0tIEJhdGNoOiBmaXJlIEJhdGNoU2l6"
    "ZSB0aW1lcywgY29uZmlybSByYXRlcyBtYXRjaCB0aGUgcGllIGFuZCBldmVyeQogICAgLy8gICAg"
    "IGV4aXQgaGFuZHMgb2ZmIGNsZWFubHkgKHRlcm1pbmFscyBlbmQsIGNvbnRpbnVlcyByb3V0ZSB0"
    "byBhIHN0dWIpLiAtLS0KICAgIHByaXZhdGUgc3RhdGljIGJvb2wgQmF0Y2hDaGVjayhSb2xsQUNv"
    "bmZpZyBjZmcsIFN0dWJQaWVHZW5lcmF0b3IgZ2VuLCBSZXNvbHZlciByZXNvbHZlciwgUG9zc2Vz"
    "c2lvblN0YXRlIHN0YXRlKQogICAgewogICAgICAgIENvbnNvbGUuV3JpdGVMaW5lKCQiLS0tIEJh"
    "dGNoOiB7Y2ZnLkJhdGNoU2l6ZTpOMH0gcG9zc2Vzc2lvbnMgKHByZXNzdXJlPTAuMDAsIHB1cmUg"
    "YmFzZSBwaWUpIC0tLSIpOwogICAgICAgIHZhciBybmcgPSBuZXcgU3lzdGVtUm5nKGNmZy5TZWVk"
    "KTsKICAgICAgICBjb25zdCBkb3VibGUgcHJlc3N1cmUgPSAwLjA7CiAgICAgICAgdmFyIHBpZSA9"
    "IGdlbi5HZW5lcmF0ZShzdGF0ZSwgcHJlc3N1cmUpOwoKICAgICAgICB2YXIgY291bnRzID0gbmV3"
    "IERpY3Rpb25hcnk8RW50cnlPdXRjb21lLCBpbnQ+KCk7CiAgICAgICAgZm9yZWFjaCAodmFyIG8g"
    "aW4gRW51bS5HZXRWYWx1ZXM8RW50cnlPdXRjb21lPigpKSBjb3VudHNbb10gPSAwOwoKICAgICAg"
    "ICB2YXIgcm91dGVkVG9TdHViID0gMDsKICAgICAgICB2YXIgZW5kZWQgPSAwOwogICAgICAgIHZh"
    "ciB1bnJvdXRlZCA9IDA7CgogICAgICAgIGZvciAodmFyIGkgPSAwOyBpIDwgY2ZnLkJhdGNoU2l6"
    "ZTsgaSsrKQogICAgICAgIHsKICAgICAgICAgICAgdmFyIHJlc3VsdCA9IFJvbGxBLkV4ZWN1dGUo"
    "c3RhdGUsIHBpZSwgcm5nLCBjZmcpOwogICAgICAgICAgICB2YXIgcm91dGluZyA9IHJlc29sdmVy"
    "LlJvdXRlKHJlc3VsdCk7CgogICAgICAgICAgICB2YXIgb3V0Y29tZSA9IHJlc3VsdCBzd2l0Y2gK"
    "ICAgICAgICAgICAgewogICAgICAgICAgICAgICAgVGVybWluYWwgPT4gRW50cnlPdXRjb21lLlNo"
    "b3RDbG9ja1Zpb2xhdGlvbiwKICAgICAgICAgICAgICAgIENvbnRpbnVlIHsgTmV4dDogQ29udGlu"
    "dWF0aW9uS2luZC5JbnRvSGFsZmNvdXJ0U2V0IH0gPT4gRW50cnlPdXRjb21lLkNsZWFuRW50cnks"
    "CiAgICAgICAgICAgICAgICBDb250aW51ZSB7IE5leHQ6IENvbnRpbnVhdGlvbktpbmQuUmVzb2x2"
    "ZVR1cm5vdmVyVHlwZSB9ID0+IEVudHJ5T3V0Y29tZS5UdXJub3ZlciwKICAgICAgICAgICAgICAg"
    "IENvbnRpbnVlIHsgTmV4dDogQ29udGludWF0aW9uS2luZC5SZXNvbHZlRm91bFR5cGUgfSA9PiBF"
    "bnRyeU91dGNvbWUuRm91bCwKICAgICAgICAgICAgICAgIENvbnRpbnVlIHsgTmV4dDogQ29udGlu"
    "dWF0aW9uS2luZC5SZXNvbHZlSnVtcEJhbGwgfSA9PiBFbnRyeU91dGNvbWUuSnVtcEJhbGwsCiAg"
    "ICAgICAgICAgICAgICBfID0+IHRocm93IG5ldyBJbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uKCJV"
    "bm1hcHBlZCByZXN1bHQuIikKICAgICAgICAgICAgfTsKICAgICAgICAgICAgY291bnRzW291dGNv"
    "bWVdKys7CgogICAgICAgICAgICBpZiAocm91dGluZy5Qb3NzZXNzaW9uRW5kZWQpIGVuZGVkKys7"
    "CiAgICAgICAgICAgIGVsc2UgaWYgKHJvdXRpbmcuRGVzdGluYXRpb24uU3RhcnRzV2l0aCgiU1RV"
    "QjoiKSkgcm91dGVkVG9TdHViKys7CiAgICAgICAgICAgIGVsc2UgdW5yb3V0ZWQrKzsKICAgICAg"
    "ICB9CgogICAgICAgIHZhciBuID0gKGRvdWJsZSljZmcuQmF0Y2hTaXplOwogICAgICAgIHZhciBy"
    "YXRlc09rID0gdHJ1ZTsKICAgICAgICBmb3JlYWNoICh2YXIgKG91dGNvbWUsIHdlaWdodCkgaW4g"
    "cGllLlNsaWNlcykKICAgICAgICB7CiAgICAgICAgICAgIHZhciBvYnNlcnZlZCA9IGNvdW50c1tv"
    "dXRjb21lXSAvIG47CiAgICAgICAgICAgIHZhciBnYXAgPSBNYXRoLkFicyhvYnNlcnZlZCAtIHdl"
    "aWdodCk7CiAgICAgICAgICAgIHZhciBwYXNzID0gZ2FwIDw9IGNmZy5SYXRlVG9sZXJhbmNlOwog"
    "ICAgICAgICAgICByYXRlc09rICY9IHBhc3M7CiAgICAgICAgICAgIENvbnNvbGUuV3JpdGVMaW5l"
    "KCQiICB7b3V0Y29tZSwtMTh9IG9ic2VydmVkPXtvYnNlcnZlZDpQM30gIGV4cGVjdGVkPXt3ZWln"
    "aHQ6UDN9ICBnYXA9e2dhcDpQM30gIHsocGFzcyA/ICJvayIgOiAiRkFJTCIpfSIpOwogICAgICAg"
    "IH0KCiAgICAgICAgdmFyIGhhbmRvZmZPayA9IHVucm91dGVkID09IDAgJiYgKGVuZGVkICsgcm91"
    "dGVkVG9TdHViKSA9PSBjZmcuQmF0Y2hTaXplOwogICAgICAgIENvbnNvbGUuV3JpdGVMaW5lKCQi"
    "ICBoYW5kb2ZmOiBlbmRlZD17ZW5kZWQ6TjB9LCByb3V0ZWQtdG8tc3R1Yj17cm91dGVkVG9TdHVi"
    "Ok4wfSwgdW5yb3V0ZWQ9e3Vucm91dGVkfSAtPiB7KGhhbmRvZmZPayA/ICJvayIgOiAiRkFJTCIp"
    "fSIpOwoKICAgICAgICByZXR1cm4gcmF0ZXNPayAmJiBoYW5kb2ZmT2s7CiAgICB9CgogICAgLy8g"
    "LS0tIFByb3ZlIHRoZSBzZWFtIGNhcnJpZXMgc2lnbmFsOiB0dXJub3ZlciByYXRlIG11c3Qgcmlz"
    "ZSB3aXRoIHByZXNzdXJlLiAtLS0KICAgIHByaXZhdGUgc3RhdGljIGJvb2wgUHJlc3N1cmVTaWdu"
    "YWxDaGVjayhSb2xsQUNvbmZpZyBjZmcsIFN0dWJQaWVHZW5lcmF0b3IgZ2VuLCBQb3NzZXNzaW9u"
    "U3RhdGUgc3RhdGUpCiAgICB7CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoIlxuLS0tIFNlYW0g"
    "c2lnbmFsOiB0dXJub3ZlciByYXRlIHZzLiBwcmVzc3VyZSAtLS0iKTsKICAgICAgICB2YXIgbG93"
    "ID0gVHVybm92ZXJSYXRlKGNmZywgZ2VuLCBzdGF0ZSwgcHJlc3N1cmU6IDAuMCk7CiAgICAgICAg"
    "dmFyIGhpZ2ggPSBUdXJub3ZlclJhdGUoY2ZnLCBnZW4sIHN0YXRlLCBwcmVzc3VyZTogMS4wKTsK"
    "CiAgICAgICAgQ29uc29sZS5Xcml0ZUxpbmUoJCIgIHR1cm5vdmVyIHJhdGUgQCBwcmVzc3VyZSAw"
    "LjAwID0ge2xvdzpQM30iKTsKICAgICAgICBDb25zb2xlLldyaXRlTGluZSgkIiAgdHVybm92ZXIg"
    "cmF0ZSBAIHByZXNzdXJlIDEuMDAgPSB7aGlnaDpQM30iKTsKCiAgICAgICAgdmFyIG1vdmVkID0g"
    "aGlnaCA+IGxvdzsKICAgICAgICBDb25zb2xlLldyaXRlTGluZSgkIiAgc2lnbmFsIGlzIGxpdmUg"
    "KGhpZ2ggPiBsb3cpOiB7KG1vdmVkID8gIm9rIiA6ICJGQUlMIil9Iik7CiAgICAgICAgcmV0dXJu"
    "IG1vdmVkOwogICAgfQoKICAgIHByaXZhdGUgc3RhdGljIGRvdWJsZSBUdXJub3ZlclJhdGUoUm9s"
    "bEFDb25maWcgY2ZnLCBTdHViUGllR2VuZXJhdG9yIGdlbiwgUG9zc2Vzc2lvblN0YXRlIHN0YXRl"
    "LCBkb3VibGUgcHJlc3N1cmUpCiAgICB7CiAgICAgICAgdmFyIHJuZyA9IG5ldyBTeXN0ZW1Sbmco"
    "Y2ZnLlNlZWQpOwogICAgICAgIHZhciBwaWUgPSBnZW4uR2VuZXJhdGUoc3RhdGUsIHByZXNzdXJl"
    "KTsKICAgICAgICB2YXIgdHVybm92ZXJzID0gMDsKICAgICAgICBmb3IgKHZhciBpID0gMDsgaSA8"
    "IGNmZy5CYXRjaFNpemU7IGkrKykKICAgICAgICB7CiAgICAgICAgICAgIGlmIChSb2xsQS5FeGVj"
    "dXRlKHN0YXRlLCBwaWUsIHJuZywgY2ZnKSBpcyBDb250aW51ZSB7IE5leHQ6IENvbnRpbnVhdGlv"
    "bktpbmQuUmVzb2x2ZVR1cm5vdmVyVHlwZSB9KQogICAgICAgICAgICAgICAgdHVybm92ZXJzKys7"
    "CiAgICAgICAgfQogICAgICAgIHJldHVybiB0dXJub3ZlcnMgLyAoZG91YmxlKWNmZy5CYXRjaFNp"
    "emU7CiAgICB9Cn0K"
)
$f_src_Charm_Harness_Program_cs_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Harness_Program_cs_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Harness\Program.cs"), $f_src_Charm_Harness_Program_cs_bytes)
Write-Host "  wrote src/Charm.Harness/Program.cs"

# src/Charm.Harness/config.json
$f_src_Charm_Harness_config_json_b64 = @(
    "ewogICJCYXNlQ2xlYW4iOiAwLjg4LAogICJCYXNlVHVybm92ZXIiOiAwLjA2LAogICJCYXNlVmlv"
    "bGF0aW9uIjogMC4wMiwKICAiQmFzZUZvdWwiOiAwLjAzLAogICJCYXNlSnVtcEJhbGwiOiAwLjAx"
    "LAogICJQcmVzc3VyZVR1cm5vdmVyTnVkZ2UiOiAwLjEwLAogICJWaW9sYXRpb25FbGFwc2VkU2Vj"
    "b25kcyI6IDMwLjAsCiAgIkVwc2lsb24iOiAxZS05LAogICJCYXRjaFNpemUiOiAxMDAwMDAsCiAg"
    "IlJhdGVUb2xlcmFuY2UiOiAwLjAwNSwKICAiU2VlZCI6IDIwMjYwNjEwCn0K"
)
$f_src_Charm_Harness_config_json_bytes = [System.Convert]::FromBase64String([string]::Join("", $f_src_Charm_Harness_config_json_b64))
[System.IO.File]::WriteAllBytes((Join-Path $root "src\Charm.Harness\config.json"), $f_src_Charm_Harness_config_json_bytes)
Write-Host "  wrote src/Charm.Harness/config.json"

Write-Host ""
Write-Host "Done. Now run:" -ForegroundColor Green
Write-Host "  dotnet run -c Release --project src/Charm.Harness"